= Anypoint Monitoring on Anypoint Platform PCE

Anypoint Platform Private Cloud Edition (Anypoint Platform PCE) includes support for Anypoint Monitoring. Anypoint Monitoring is a suite of tools that provides feedback from Mule flows and components in your application network.

Anypoint Monitoring is an add-on to Anypoint Platform PCE. To use Anypoint Monitoring with Anypoint Platform PCE, contact MuleSoft Professional Services.

Using Anypoint Monitoring with Anypoint Platform PCE requires the "Monitoring for On-Premises Management" subscription. This subscription entitles you to use two monitoring instances. A monitoring instance is an implementation of the 3-node Anypoint Monitoring configuration described in xref:supported-cluster-config.adoc[Supported Configurations for Anypoint Platform PCE]. Each monitoring instance is dedicated to a single Anypoint Platform PCE installation.

To use Anypoint Monitoring with more than two Anypoint Platform PCE installations, you must purchase additional monitoring subscriptions. Contact MuleSoft Professional Services for more information.

== Supported Anypoint Monitoring Features

|===
| Feature | Gold and Platinum Subscription Features | Titanium Subscription Features | Anypoint Platform PCE Features

|Dedicated infrastructure for data processing and storage
|No
|Yes
|Yes

|Custom metrics
|No
|Yes
|Yes

4+| *Built-in Application Dashboards*
|More than 80 out-of-the-box charts covering metrics in the following categories: Overview, Inbound, Outbound, Performance, Failures, JVM, and Infrastructure

|Yes
|Yes
|Yes

|Advanced metrics for Inbound and Outbound charts
|No
|Yes
|Yes

|Flows charts
|No
|Yes
|Yes

|Connectors charts
|No
|Yes
|Yes

|Anypoint Visualizer application network integration
|No
|Yes
|Yes

|xref:monitoring::performance-and-impact.adoc#data-retention-and-aggregation[Data retention] for more than 30 days
|No
|Yes
|Yes

4+| *Built-in API Dashboards*

|16 out-of-the-box charts covering metrics in the following categories: Overview, Requests, Failures, Performance, and Client Application 
|Yes
|Yes
|Yes

|xref:monitoring::performance-and-impact.adoc#data-retention-and-aggregation[Data retention] for more than 30 days
|No
|Yes
|Yes

4+| *Custom Dashboards*

|Basic mode
|Yes
|Yes
|Yes

|Advanced mode
|Yes, with limited functionality
|Yes
|Yes

|Advanced mode with additional features
|No
|Yes
|Yes

4+| *Alerts*

|Basic alerts
|Yes
|Yes, with xref:monitoring::performance-and-impact.adoc#data-retention-and-aggregation[higher limits]
|Yes

|Advanced alerts
|No
|Yes
|Yes

4+| *Log Management*

|Log search
|No
|Yes
|No

|Log points
|No
|Yes
|No

|Raw data
|No
|Yes
|No

4+| *Additional Anypoint Monitoring features*

|Anypoint Monitoring Archive API
|No
|Yes
|No

|xref:api-functional-monitoring[API Functional Monitoring] +
|Yes
|Yes
|Yes

|Reports
|No
|Yes
|Yes

4+| *Enhanced Support*

|Enhanced Support
|No
|Yes
|No

|===

=== Unsupported Anypoint Monitoring Features

Anypoint Platform PCE does not the support the following Anypoint Monitoring features:

** Support for Mule 3.8.x
** Log management
+
As an alternative, use your server's logging capabilties or a third-party vendor like Splunk.
** Increased storage capacity
+
This capacity is not required because the Archive API is not supported.
** Archive API
+
This API is not applicable because log management is not supported.
** API Functional Monitoring
+
As an alternative, use a third-party vendor, such as Pingdom.
** The *Tools* option in the left-hand menu is not available.

== Requirements

Anypoint Monitoring has disk and network port requirements in addition to the Anypoint Platform PCE requirements.

For information, see xref:prereq-hardware.adoc[Hardware Prerequisites].

== Backup and Restore

Anypoint Monitoring backup and restore are outside the normal gravity backup and restore mechanism, and require the additional procedures. 
For information, see xref:backup-and-disaster-recovery.adoc[Configure Backup and Restore for Anypoint Platform PCE].

== Uninstall Anypoint Monitoring

If you want to uninstall the Anypoint Monitoring add-on, contact MuleSoft services.

== See Also

* xref:prereq-hardware.adoc[Hardware Prerequisites]
* xref:backup-and-disaster-recovery.adoc[Configure Backup and Restore for Anypoint Platform PCE]
* xref:monitoring::index.adoc[Anypoint Monitoring Overview]

