= Anypoint Monitoring and Visualizer

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Requirements

=== Stateful Set Directories

Each stateful set uses a different directory to hold its data.

* InfluxDB meta pods (3 pods): `/var/lib/data/influxdb/meta`
* Data pods (2 pods): `/var/lib/data/influxdb/data`
* Logstash: `/var/lib/data/logstash`
* Insight: `/var/lib/data/dias-cassandra` and `/var/lib/data/dias-meld`

=== Port Requirements

The required ports must be accessible in the main balancer, including port 8895.

== Backup and Restore

Anypoint Monitoring and Visualizer backup and restore are outside the normal Gravitational backup and restore mechanism, and require additional procedures.

These components store metrics and other information, but they do not store platform configuration.

Anypoint Monitoring and Visualizer must back up the data of the component InfluxDB (`dias-prov-k8s-am-influxdb-comp`).

Anypoint Monitoring and Visualizer holds configuration for the Monitoring and Visualizer components in a Postgres database. The default Gravitational mechanism backs up and restores this database.

Anypoint Monitoring and Visualizer requires 4 TB volumes for `amv` nodes. A full InfluxDB backup can be up to 8 TB of data. (Only two data nodes are operative.)

You must provide enough free space on the target directory for the entire backup.

Restore time is proportional to the size of the backup.

During restore, existing data on the target cluster will be backed up and erased upon user approval.

The script must be run on a `master` node and must have `sudo` access because it uses `kubectl`.

The script validates the restore disk size, databases, measurements, retention policies, and series cardinality for all measurements in each database.

=== Procedure

The InfluxDB backup and restore script is in these locations:

* Git repository: `https://github.com/mulesoft/anypoint/tree/develop/resources/3.0/kubernetes/amv-backup-restore/amv-backup-restore.sh`
* In the PCE environment: `/var/lib/gravity/site/packages/unpacked/gravitational.io/anypoint/3.0.0*/resources/kubernetes/amv-backup-restore/amv-backup-restore.sh`

The script has these parameters:

----
 -a : (Required) action to perform : backup or restore. [string].
        Default NO DEFAULT ACTION.
 -v : (optional) verbose output.
        Default non-verbose.
 -f : (Required) name of the tar file.
        Default for backup : dias-prov-k8s-am-influxdb-comp_YYYYMMD.  [string].
        Default for restore : /var/lib/data/influxdb/backup/dias-prov-k8s-am-influxdb-comp_YYYYMMDD.tar.gz.  [Full Path].
 -d : (Required for backup) full path to location where backup tar file is stored.
        Default for backup : /var/lib/data/influxdb/backup. [Full Path].
        Default for restore : same as tar file path. [Full Path].
 -s : (optional) Optional sub-component filter, use only for backup of only meta or only data.
 -h : Print HELP.
----

=== Examples

Verbose backup: `sudo bash amv-backup-restore.sh -va backup -f 2020-01-01-influxdb-backup -d path/to/backup/dir`

Non-verbose restore: `sudo bash amv-backup-restore.sh -a restore -f /var/lib/data/influxdb/backup/dias-prov-k8s-am-influxdb-comp_YYYYMMDD.tar.gz`

== Uninstall Anypoint Monitoring and Visualizer

If you wish to uninstall the Anypoint Monitoring and Visualizer Add-on, please contact MuleSoft services.
