= Anypoint Monitoring and Visualizer

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Overall Architecture

Anypoint Monitoring is an optional feature during installation, which includes Anypoint Visualizer. Both products require 3 dedicated nodes, normally labeled *amv_node*.

In those 3 nodes, the following Helm charts will be installed in 4 different namespaces:

. `dias`

.. dias-prov-k8s-am-influxdb-comp
.. dias-prov-k8s-am-ingestor-comp
.. dias-prov-k8s-amr-certs-comp
.. dias-prov-k8s-amr-ingestor-router-comp
.. dias-prov-k8s-insight-comp
.. dias-provisioning-api

. `monitoring-center`

.. monitoring-center-alerts-api
.. monitoring-center-metrics-api
.. monitoring-center-settings-api
.. monitoring-center-ui
.. monitoring-center-ui-api
.. monitoring-center-visualizer

. `default`

.. stolon-amv

. `visualizer`
.. visualizer-experience-api
.. visualizer-janitor
.. visualizer-topology-api
.. visualizer-topology-processor
.. visualizer-ui

It's important to mentioned that a dedicated Stolon DB will be deployed in addition to the one used by the platform.

=== DIAS Components

DIAS provides the foundations for data transmission between the Mule runtime (running Filebeat) and the InfluxDB storing that data. Once data reaches InfluxDB, it becomes available to the Anypoint Monitoring UI as well as the Insight alerting engine.

The `dias-prov-k8s-amr-ingestor-router-comp` pods run Nginx accepting connections from remote runtimes thought mTLS (it uses a node-port service). Data is then forwarded to `dias-prov-k8s-am-ingestor-comp` pods running Logstash.

Logstash processes and transform those messages and batch them before hitting InfluxDB. The `dias-prov-k8s-am-influxdb-comp` component is a stateful InfluxDB cluster consisting in 3 meta and 2 data nodes.

The Insight alerting engine is managed by the `dias-prov-k8s-insight-comp` component. It periodically fetches metrics from InfluxDB and based on the customer's alerts definition, the engine triggers alarms. Each pod has 4 containers, including a Mule application, Meld, Meld-Drill and Cassandra.

Logstash, Insight and InfluxDB are all K8s stateful sets.


=== Monitoring Center Components

Mati

=== Visualizer Components

Yevhen



self-signed certs

== Considerations

=== Cluster secrets

All Anypoint Monitoring/Visualizer components use self-signed certificates for TLS support. Those certificates are generated by the `dias-prov-k8s-amr-certs-comp` components and stored as secrets within the cluster under the `dias` namespace. It is important to notice if the customer changes the platform DNS, the `dias-prov-k8s-amr-certs-comp` will be redeployed and secrets will be updated. Additionally, the `dias-prov-k8s-amr-ingestor-router-comp` component, running Nginx, will be redeployed as well, refreshing those new secrets.

=== Stateful sets directories

Each stateful set uses different directories to hold its data, resulting in the following directories:

---
  /var/lib/data/influxdb/data
  /var/lib/data/influxdb/meta
  /var/lib/data/logstash
  /var/lib/data/dias-cassandra
  /var/lib/data/dias-meld

InfluxDB meta pods (3 pods) use `/var/lib/data/influxdb/meta` while data pods use `/var/lib/data/influxdb/data`. Logstash uses `/var/lib/data/logstash` and finally Insight uses the remaining two directories to hold its data.

== Requirements

hardware, ports, certs, directories...

CPU, memory, fetches


=== InfluxDB License

== Restore/Backup

required size

----
openssl dhparam 2048 -out dhparam.pem
----
