= Anypoint Monitoring and Visualizer

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Considerations

=== Stateful sets directories

Each stateful set uses different directories to hold its data, resulting in the following directories:

```
  /var/lib/data/influxdb/data
  /var/lib/data/influxdb/meta
  /var/lib/data/logstash
  /var/lib/data/dias-cassandra
  /var/lib/data/dias-meld
```

InfluxDB meta pods (3 pods) use `/var/lib/data/influxdb/meta` while data pods (2 pods) use `/var/lib/data/influxdb/data`. Logstash uses `/var/lib/data/logstash` and finally Insight uses the remaining two directories to hold its data.

=== Port Requirements

Port 8895 needs to be accesible in the main balancer along with the rest of the required ports.

== Backup/Restore

Both backup and restore procedures for Anypoint Monitoring are outside the normal Gravitational backup/restore mechanism and therefore requires additional procedures.

Anypoint Monitoring/Visualizer need to backup the following component's data

. InfluxDB (`dias-prov-k8s-am-influxdb-comp`)

It is important to mentioned that the Anypoint Monitoring/Visualizer custom Stolon DB will be backup/restore by the default Gravitational mechanism and it is not considered in this document.


=== IMPORTANT
 . Anypoint Monitoring/Visualizer requires 4TB volumes for `amv` nodes and therefore a InfluxDB full backup can be up to 8TB of data (only two data nodes are operative)
 . It's up to the customer to provide enough free space on the target directory for the entire backup.
 . Restore time is proportional to size of the backup
 . During restore, existing data on target cluster will be backed-up and erased upon user approval
 . Script must be run on a `master` node and must be SUDO as it uses kubectl
 . The script validates the restore disk size, databases, measurements, retention policies and series cardinality for all measurements in each DB


=== Procedure

InfluxDB backup/restore mechanism is based in a single script located in.

- Git Repo:
  `https://github.com/mulesoft/anypoint/tree/develop/resources/3.0/kubernetes/amv-backup-restore/amv-backup-restore.sh`.
- Location on PCE environment:
  `/var/lib/gravity/site/packages/unpacked/gravitational.io/anypoint/3.0.0*/resources/kubernetes/amv-backup-restore/amv-backup-restore.sh`.

The script requires the following parameters:

 -a : (Required) action to perform : backup or restore. [string].
        Default NO DEFAULT ACTION.
 -va : (optional) verbose output.
        Default non-verbose.
 -f : (Required) name of the tar file.
        Default for backup : dias-prov-k8s-am-influxdb-comp_YYYYMMD.  [string].
        Default for Restore : /var/lib/data/influxdb/backup/dias-prov-k8s-am-influxdb-comp_YYYYMMDD.tar.gz.  [Full Path].
 -d : (Required for backup) full path to location where backup tar file is stored.
        Default for backup : /var/lib/data/influxdb/backup. [Full Path].
        Default for restore : same as tar file path. [Full Path].
 -s : (optional) Optional sub-component filter, use only for backup of only meta or only data.
 -h : Print HELP.

=== Examples

. Verbose backup => `sudo bash amv-backup-restore.sh -va backup -f 2020-01-01-influxdb-backup -d path/to/backup/dir`

. Non Verbose restore => `sudo bash amv-backup-restore.sh -a restore -f /var/lib/data/influxdb/backup/dias-prov-k8s-am-influxdb-comp_YYYYMMDD.tar.gz`

== Uninstall Anypoint Monitoring and Visualizer

If you wish to uninstall the Anypoint Monitoring and Visualizer Add-on, please contact MuleSoft services.
