= Anypoint Monitoring and Visualizer

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Requirements

=== Stateful Set Directories

Each stateful set uses a different directory to hold its data.

* InfluxDB meta pods (3 pods): `/var/lib/data/influxdb/meta`
* Data pods (2 pods): `/var/lib/data/influxdb/data`
* Logstash: `/var/lib/data/logstash`
* Insight: `/var/lib/data/dias-cassandra` and `/var/lib/data/dias-meld`

=== Port Requirements

The required ports must be accessible in the main balancer, including port 8895.

== Backup and Restore

Anypoint Monitoring and Visualizer backup and restore are outside the normal Gravitational backup and restore mechanism, and require the additional procedures described in the Anypoint Private Cloud backup and restore documentation.

== Uninstall Anypoint Monitoring and Visualizer

If you wish to uninstall the Anypoint Monitoring and Visualizer Add-on, please contact MuleSoft services.

== See Also

* xref:backup-and-disaster-recovery.adoc[Configure Backup and Restore for Anypoint Private Cloud]
