= Configure Backup and Restore for Anypoint Private Cloud
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To preserve your data in case of system failure or problems with other operations, such as patching or performing upgrades, ensure that your system is automatically backed up. Regular backups are extremely important for disaster recovery procedures. Configure your backup to run at least once per day; hourly is recommended. Store your backup archive on external storage outside the Anypoint Platform cluster.

Anypoint Platform Private Cloud Edition (Anypoint Platform PCE) requires you to install, configure, and manage an NFS server. Ensure that you configure and perform frequent backups of this server.

== Create a Backup

To create a backup, run the following command on any node in the cluster:

----
gravity backup /var/lib/gravity/planet/share/backup.tar.gz
----

This command creates an archive of the current system state in: `/var/lib/gravity/planet/share/backup.tar.gz`. You can pass the following optional parameters to the gravity backup command:

* `--follow`
+
Outputs the backup job logs to stdout.
* `--timeout`
+
Specifies the deadline for the backup job, for example, 30s or 5m. Default is 20m.
* `--log-file`
+
Outputs logs to a file.

Backup contents:

[%header%autowidth.spread]
|===
| Information | Included in PCE Backup 
| Databases | Y
| Configurations | Y
| Secrets | Y
| Object Store | Y
| Disclaimer settings | Y
| SMTP settings | Y
| DNS settings | N
| Platform Certificate | N
| NFS settings | N
| NFS files | N	
| Drives | N
| Runtimes* | N	
|===
 
*PCE only has INFORMATION about runtimes, such as their names and status.

== Perform a System Restore

To restore a system from your backup archive, use the original cluster or create a new cluster.

[WARNING]
====
Some settings, including NFS, certificates, and DNS, are not backed up and must be configured for the environment in which the restore will be performed *before* running the restore.
====

[WARNING]
====
You cannot perform a backup between different versions of Anypoint Platform PCE. The new installation you create must use the same version of Anypoint Platform PCE as your backup.
====

. Log in to one of the nodes in your cluster.

. Move the compressed backup archive file to a folder on any master node in the environment to be restored. You can transfer this file securely via the following command:
+
----
scp /backup-path/to-restore.tar.gz your_username@remotehost.edu:/var/lib/gravity/planet/share
----

. Restore the cluster from the backup archive:
+
----
sudo gravity restore /var/lib/gravity/planet/share/to-restore.tar.gz
----
+
You can pass the following optional parameters:
+
====
* `--follow`
+
Outputs the restore job logs to stdout.
* `--timeout`
+
Specifies the maximum time allowed for the backup operation, for example, 30s, 5m, and so on. The default value is `80m`. If you have a very large number of applications and files, use a minimum of `160m` as the `--timeout` value.
* `--log-file`
+
Outputs logs to a file.
====

. Wait for the operation to complete, which is typically forty to sixty minutes.

. Manually restore the NFS files if you are not reusing the original NFS.

== See Also

* xref:install-workflow.adoc[Install Anypoint Platform Private Cloud]
* xref:upgrade.adoc[Upgrade Anypoint Platform Private Cloud]
