= Configure Backup and Restore for Anypoint Platform PCE
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To preserve your data in case of system failure or problems with other operations, such as patching or performing upgrades, ensure that your system is automatically backed up. Regular backups are extremely important for disaster recovery procedures. Configure your backup to run at least once per day; or more often depending on your requirements. Store your backup archive on external storage outside the Anypoint Platform cluster.

Anypoint Platform Private Cloud Edition (Anypoint Platform PCE) requires you to install, configure, and manage an NFS server. Ensure that you configure and perform frequent backups of this server.

[IMPORTANT]
====
Backup and restore for Anypoint Monitoring and Anypoint Visualizer are performed outside the normal PCE backup and restore mechanism, and require a separate procedure.
====

== Create a Backup

. To create a backup, run the following command:
+
----
curl -k https://<platformDns>/platform/backup \
  -X POST \ -H "Authorization: Bearer $token" \
  -H "Content-Type:application/json" \
  -d '{"nfs-server": "<nfsServer>", "nfs-path": "<nfsPath>", "backup-file-name": "backup.tar.gz" }'
----

. This command creates an archive of the current system state in the provided NFS with the name: `backup.tar.gz`. It also outputs a JSON response with the status of the operation and the job name:
+
----
{"success":"backup job triggered","jobName":"<anypoint-backup-job-id>"}
----

. To stream the backup job logs to stdout run:
+
----
kubectl logs jobs/<anypoint-backup-job-id> -f
----

Backup contents:

[%header%autowidth.spread]
.Backup Contents
|===
| Information | Included in PCE Backup 
| Databases | Y
| Configurations | Y
| Secrets | Y
| Object Store | Y
| Disclaimer settings | Y
| SMTP settings | Y
| DNS settings | N
| Platform certificate | N
| Ops Center certificate | N
| NFS settings | N
| NFS files | N	
| Drives | N
| Runtimes* | N	
| Anypoint Monitoring metrics | N
|===
 
*Anypoint Platform PCE has information only about runtimes, such as their names and status.

== Perform a System Restore

To restore a system from your backup archive, use the original cluster or create a new cluster.

[WARNING]
====
Some settings, including NFS, certificates, and DNS, are not backed up and must be configured for the environment in which the restore will be performed before running the restore.
====

. Move the compressed backup archive file to an NFS Server.

. Restore the cluster from the backup archive:
+
----
curl -k https://<platformDns>/platform/restore \
  -X POST \ -H "Authorization: Bearer $token" \
  -H "Content-Type:application/json" \
  -d '{"nfs-server": "<nfsServer>", "nfs-path": "<nfsPath>", "backup-file-name": "backup.tar.gz" }'
----

. It outputs a JSON response with the status of the operation and the job name:
+
----
{"success":"restore job triggered","jobName":"<anypoint-restore-job-id>"}
----

. To stream the backup job logs to stdout:
+
----
kubectl logs jobs/<anypoint-restore-job-id> -f
----

. Wait for the operation to complete, which is typically 40 to 60 minutes.
. Manually restore the NFS files if you are not reusing the original NFS.

== Anypoint Monitoring and Anypoint Visualizer

If Anypoint Monitoring and Anypoint Visualizer are enabled, follow these procedures to back up and restore them.

Anypoint Monitoring and Anypoint Visualizer backup and restore are outside the normal PCE backup and restore mechanism, and require additional procedures. These components store metrics and other information, but they do not store platform configuration. Platform configuration information is handled by the system backup and restore procedures.

Anypoint Monitoring and Anypoint Visualizer must back up the data of the component InfluxDB (`dias-prov-k8s-am-influxdb-comp`). Anypoint Monitoring and Anypoint Visualizer both store their configuration data in a Postgres database. The default PCE mechanism backs up and restores this database.

Anypoint Monitoring and Anypoint Visualizer requires 4 TB volumes for `amv` nodes. A full InfluxDB backup can be up to 8 TB of data. (Only two data nodes are operative.) You must provide enough free space on the target NFS server for the entire backup.

Restore time is proportional to the size of the backup. During restore, existing data on the target cluster will be backed up and erased upon user approval.

The job validates the restore disk size, databases, measurements, retention policies, and series cardinality for all measurements in each database.

=== Procedure

==== AMV Backup
. Run the amv backup operation
+
----
curl -k https://<platformDns>/platform/amv/backup \
  -X POST \ -H "Authorization: Bearer $token" \
  -H "Content-Type:application/json" \
  -d '{"nfs-server": "<nfsServer>", "nfs-path": "<nfsPath>", "backup-file-name": "amv_backup.tar.gz" }'
----
. It outputs a JSON response with the status of the operation and the job name:
+
----
{"success":"backup job triggered","jobName":"<amv-backup-job-id>"}
----
. To stream the backup job logs to stdout:
+
----
kubectl logs jobs/<amv-backup-job-id> -f
----

==== AMV Restore
. Move the compressed backup archive file to an NFS Server.

. Restore the cluster from the backup archive:
+
----
curl -k https://<platformDns>/platform/amv/restore \
  -X POST \ -H "Authorization: Bearer $token" \
  -H "Content-Type:application/json" \
  -d '{"nfs-server": "<nfsServer>", "nfs-path": "<nfsPath>", "backup-file-name": "amv_backup.tar.gz" }'
----

. It outputs a JSON response with the status of the operation and the job name:
+
----
{"success":"restore job triggered","jobName":"<amv-restore-job-id>"}
----

. To stream the backup job logs to stdout:
+
----
kubectl logs jobs/<amv-restore-job-id> -f
----


== See Also

* xref:install-workflow.adoc[Install Anypoint Platform Private Cloud]
* xref:upgrade.adoc[Upgrade Anypoint Platform Private Cloud]
