= Configuring Backup and Restore for Anypoint Platform PCE
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Platform Private Cloud Edition (Anypoint Platform PCE) requires you to install, configure, and manage an NFS server, ensuring frequent backups are configured and performed.

To preserve your data:

* Enable automatic backups to protect against system failures or operational issues.
* Schedule backups at least daily, or more frequently based on your needs.
* Store backups externally, outside the Anypoint Platform cluster.

The backup and restore process is controlled via Anypoint Platform PCE APIs.

== Create a Backup

To create a backup, run the following command:

`curl -k <platform-dns>/platform/backup-X POST -H 'Authorization: Bearer ${token}' -H 'Content-Type: application/json' -d '{"backup-file-name": "${backupFileName}.tar.gz", "nfs-server": "${fileSystemDns}", "nfs-path": "/"}'`

=== Backup Content

[%header%autowidth.spread]

|===
| Information | Included in Anypoint Platform PCE Backup 
| Databases | Yes
| Configurations | Yes
| Secrets | Yes
| Object Store | Yes
| Disclaimer settings | Yes
| SMTP settings | Yes
| DNS settings | No
| Platform certificate | No
| NFS settings | No
| NFS files | No	
| Drives | No
| Runtimes* | No	
| Anypoint Monitoring metrics | No
|===
 
*Anypoint Platform PCE has information only about runtimes, such as their names and status.

== Perform a System Restore

Consider the following before you perform a system restore:

* Before running a restore, configure certain settings, such as NFS, certificates, and DNS because they are not included in the backup.
* Backups cannot be transferred between different versions of Anypoint Platform PCE; therefore, your new installation must match the version of your backup.

To perform the restore, run the following command:

`curl -k <platform-dns>/platform/restore-X POST -H 'Authorization: Bearer ${token}' -H 'Content-Type: application/json' -d '{"backup-file-name": "${backupFileName}.tar.gz", "nfs-server": "${fileSystemDns}", "nfs-path": "/"}`

The backup file is stored on the NFS storage.

== Create an InfluxDB Backup

To create an InfluxDB backup, run the following command:

`curl -k <platform-dns>/platform/amv/backup-X POST -H 'Authorization: Bearer ${token}' -H 'Content-Type: application/json' -d '{"backup-file-name": "${backupFileName}.tar.gz", "nfs-server": "${fileSystemDns}", "nfs-path": "/"}'`

== Perform an InfluxDB Restore

To perform an InfluxDB restore, run the following command:

`curl -k <platform-dns>/platform/amv/restore-X POST -H 'Authorization: Bearer ${token}' -H 'Content-Type: application/json' -d '{"backup-file-name": "${backupFileName}.tar.gz", "nfs-server": "${fileSystemDns}", "nfs-path": "/"}'`

The backup file is stored on the NFS storage.

== See Also

* xref:operating-about.adoc[]
* xref:install-workflow.adoc[Installing Anypoint Platform Private Cloud]
* xref:upgrade.adoc[Upgrade Anypoint Platform Private Cloud]
