
= Configure Alerts for Anypoint Private Cloud
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Platform Private Cloud Edition (Anypoint Platform PCE) provides built-in alerts that are triggered when a condition defined in any alert definition is detected.

Measurements are stored in https://www.influxdata.com/products/influxdb-overview[Influxdb]. https://www.influxdata.com/time-series-platform/kapacitor[Kapacitor] reads the measurements and sends emails when an alert is triggered.

== Alert Definitions

* High CPU: Measures the total CPU usage on all cluster nodes. Threshold: Warning 75%, Critical 90%

* High Memory: Measures the memory consumption on all cluster nodes. Threshold: Warning 75%, Critical 90%

* Filesystem Usage: Measures the file system usage. Threshold: Warning 80%, Critical 90%

* Kubernetes Node Status: Checks Kubernetes status for all nodes. Threshold: When Kubernetes reports a `NotReady` node status

* Etcd Latency: Measures the latency between nodes. Latency can affect `etcd` (the database that stores the Kubernetes state) performance. Threshold: Warning 521, Critical 1024

* Systemd health: Checks if the `systemd` slice (where gravity is running) is not healthy. Threshold: When gravity or child systems, such as `docker`, `etcd`, `kube-proxy`, `kube-kubelet`, `planet-agent`, `dnsmasq`, and `flanneld`, are down

* Influxdb Healthcheck Status: Checks the health of `Influxdb` (where the metrics for monitoring are stored). Threshold: No connection to `Influxdb`

* Networking Configuration: Checks networking operating system flag status. Threshold: When `ip_forward` or `br_netfilter` flags are disabled

* Node Uptime: Checks if nodes are online. Threshold: When a node is down for more than 5 minutes.

* Etcd Health: Checks the status of `etcd`. Threshold: When `etcd` is down or not healthy.

* Docker Status: Verifies the docker service is running on each node. Threshold: When docker service is not running on a node.

* Backup Failing: Checks the result of a backup operation. Threshold: When a backup operation fails.

* Stolen Replication Lag: Checks if a `Postgres` replica is out of sync. Threshold: When a replica is lagging by 1800 or more seconds.

[NOTE]
The backup alert is defined in the *backup-status-alert* configmap.
The *Cassandra Load* alert is defined in _cassandra-load_ configmap.

== Configure Alert Definitions 

. From OpsCenter, navigate to *Configuration*.
. Select the *monitoring* namespace.
. Select a configmap and apply your changes.

If you apply changes to the `kapacitor-alerts` configmap, you must restart Kapacitor. Follow the instructions in the Restart Kapacitor section in this topic.

== Configure Alerts

. Configure the `FROM` and `TO` email addresses:
.. Log in to the Ops Center console and then select *Configuration*.
.. From the *Namespace* drop-down, select *monitoring*.
.. From the *Config maps* drop-down, select *alerting-addresses*.
.. Select *From* and then enter the `FROM` email address used for the alert.
.. Select *To* and then enter the `TO` email address used for the alert.

. Configure your SMTP email server to send alerts. Configuring the SMTP server in Anypoint Access Management restarts the Anypoint Platform service responsible for initiating alerts.
+
To ensure that alerts work correctly:
+
** Verify that your SMTP server can send and receive emails using the addresses you configure as the `FROM` and `TO` addresses in the following section.
** Verify that your cluster nodes can communicate with your SMTP server. For example, use `telnet` to connect to your SMTP server from one of your cluster nodes:
+
----
telnet my.smtp.server.com 587
Trying XXX.XXX.XXX.XXX...
Connected to my.smtp.server.com.
Escape character is '^]'.
220 my.smtp.server.com ESMTP
^[^]
telnet> quit
Connection closed.
----

== Troubleshooting

If the connection is working, you can check Kapacitor logs for other errors when sending email alerts. 
On Ops Center, you can retrieve log information in the console ouput by running the following command: 
+
----
kubectl logs -n monitoring -l component=kapacitor -c kapacitor
----

== Restart Kapacitor
When you change the SMTP settings from Access Management, Kapacitor is automatically restarted to include the updated settings. 

If you change an alert definition or the `alerting-addresses` configmap without changing the SMTP settings from Access Management, Kapacitor must be manually restarted:

. Open a terminal to one of the master servers.
. Run the following command:
+
```
`kubectl delete pod -n monitoring -l component=kapacitor`
```
. Wait for a `kapacitor` pod to run. Run the following command for verification:
+
```
kubectl get pod -n monitoring -l component=kapacitor` 
```

== See Also

* xref:managing-via-the-ops-center.adoc[Ops Center]
