= Post-installation Checklist
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The following tasks are required after you complete Anypoint Platform Private Cloud Edition installation. Otherwise, you cannot deploy and manage applications, register APIs, and use API Exchange on an Anypoint Platform environment running on your own local network. Refer to xref:install-checklist.adoc[Installation Checklist] for more information.

* xref:access-management-dns.adoc[Configure DNS on Anypoint Private Cloud]
* xref:access-management-security.adoc[Configure Security on Anypoint Private Cloud]
* xref:access-management-SMTP.adoc[Configure SMTP in Anypoint Private Cloud]
* xref:install-config-ldap-pce.adoc[Configure an External Identity Provider in Anypoint Private Cloud]
* xref:backup-and-disaster-recovery.adoc[Configure Backup and Restore] 

[NOTE]
At the time of this writing, some Docker containers must run as root. Processes running as root do not expose functionality outside the cluster. 
Processes that serve external traffic do not run as root, to maximize security.

== See Also

* xref:runtime-manager::managing-servers.adoc[About Servers, Server Groups, and Clusters]
* xref:api-manager::custom-policy-uploading-to-exchange.adoc[Uploading Custom Policies]
* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/exchange-maven-facade-api-http/[Maven facade API]
