= Allow Addresses for API Platform Proxies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Registered Domains

Every HTTP request you make to an external resource goes through the API Console Proxy. For security reasons, you need to register the domain as an allowed or blocked domain in Anypoint Platform. 

By default, proxy requests are blocked for new domains on authenticated requests.

To add a new domain:

1. Log in to Anypoint Platform using an account that has the Organization Administrator permission.

2. In the navigation bar or the main Anypoint Platform page, click *Access Management*.

3. Click *Registered domains*.

4. Click *Add domain*. +
The domain must not match with any existing domain, and must not be any domain or subdomain of MuleSoft or Anypoint Platform.

5. Under Trust level, select if you want the domain to be *Allowed* or *Blocked*.

6. In the dialog box that appears, type the domain name and click Add domain. +

Result: The domain has been added to your list of registered domains. You are redirected to the registered domains page, where you can edit or delete your domains. If you register a domain on a parent organization, it is also allowlisted on all your business groups.

== Authentication 

=== Strict Authentication


=== Non-strict Authentication 

@devs I need more information on what exactly should be documented on the authentication section, if we do need one.


