= Allow Addresses for API Platform Proxies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

By default, proxy requests are enabled for the domain name where the platform is running. 

To allow addresses:

. Log in to Ops Center and select *Kubernetes* on the left side-bar.
. Select the `api-manager` namespace from the drop-down menu on the top, and then select *Configmaps*. Find the `api-platform-web-env` configmap and then click on `Edit Config Map`.
. Select the *APW_FEATURES_PROXYWHITELIST* tab and ensure that value is set to `true`. (You'll have to hover your mouse over the tabs to get a tooltip with the full name to find the right tab)
+
If not, set it to `true` and then select `Apply`.
. Select the *APW_PROXYWHITELIST_RULES* tab.
. Write your rules separated by commas.
+
The following example defines regular expressions that allow requests to be made to the `*.somewhere.com/*` and `*.somewhereelse.com/*` domains, where `*` is any part of a DNS name or URL:

----
.*\.somewhere\.com,.*\.somewhereelse\.com
----

. Select *Apply* to save changes to the `api-platform-web-env` config map.
. Re-create the pods to ensure that each node in the cluster uses the most recent configuration:
+
----
kubectl delete pod -n api-manager -l component=api-platform-web
----

NOTE: This method is currently working from version 3.2.0 to version 3.2.1. From version 3.2.2 and any future versions, refer to Trusted Domains.

== Trusted Domains

Every HTTP request you make to an external resource goes through the API Console Proxy. For security reasons, you need to register the domain as an allowed domain in Anypoint Platform. 

By default, proxy requests are blocked for external domains on authenticated requests.

To add a new domain:

1. Log in to Anypoint Platform using an account that has the Organization Administrator permission.

2. In the navigation bar or the main Anypoint Platform page, click *Access Management*.

3. Click *Trusted domains*.

4. Click *Add domain*. +
The domain must not match with any existing domain,  must not be any domain or subdomain of MuleSoft or Anypoint Platform, and should be written in the format `exampledomain.com`.
NOTE: Regular expressions are not supported at the moment.

5. In the dialog box that appears, type the domain name and click Add domain. +

Result: The domain has been added to your list of trusted domains. You are redirected to the trusted domains page, where you can edit or delete your domains. If you register a domain on a parent organization, it is also allowlisted on all your business groups.

== Authentication 

When using the proxy, there are two authentication modes available: 

*Strict Authentication*: All requests reaching the proxy must be authenticated. This means that user token credentials must be included in the ms-authorization header of the request. This is the default option.

WARNING: Requests to external domains from the Exchange Public Portals will fail, as there is no Anypoint user involved in the event, and external domains require authentication.

*Non-Strict Authentication*: ACP continues to be unauthenticated, but also allows unauthenticated requests. The incoming request must provide either the users credentials or a reference ot the Organization ID that the request belongs to.

To change the authentication method from strict to non-strict, follow these steps:

. Log in to Ops Center and select *Kubernetes* on the left side-bar.
. Select the `api-console-proxy` namespace from the drop-down menu on the top, and then select *Configmaps*. Find the xservice-env` configmap and then click on *Edit Config Map*.
. Select the *STRICT_AUTHENTICATION_FF* tab and ensure that the value is set to `false`. (You'll have to hover your mouse over the tabs to get a tooltip with the full name to find the right tab)
. Select *Apply* to save changes to the `service-env` config map.
. Re-create the pods to ensure that each node in the cluster uses the most recent configuration:
+
----
kubectl delete pod -n api-console-proxy -l component=service
----



