= Add Whitelist Addresses for API Platform Proxies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

By default, proxy requests are enabled for the domain name where the platform is running.

To add whitelist addresses:

. Log in to Ops Center and select Configuration.
. Select the `api-manager` namespace on the right dropdown and then select`api-platform-web-env` config map on the left dropdown.
. Locate the `APW_FEATURES_PROXYWHITELIST`, click it and ensure that is set to `true`. If not, set it to `true` and click the `Apply` button on the bottom.
+
. Locate the `APW_PROXYWHITELIST_RULES` tab and click it:
+
. Write your rules separated by commas. The following example shows how to define regular expressions to allow requests to be made to the `*.somewhere.com/*` and `*.somewhereelse.com/*` domains, where * is any part of a DNS name or URL:
+
----
.*\\.somewhere\\.com,.*\\.somewhereelse\\.com 
----

. Select Apply to save changes to the `api-platform-web-env` config map.
. Recreate the pods to ensure each node in the cluster uses the most recent configuration:
+
----
kubectl delete pod -n api-manager -l component=api-platform-web
----
