
= PCE Alerts Configuration
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

There is a set of out of the box alerts for PCE triggered when a condition defined in each alert definition is detected.

Measures are stored in [Influxdb](https://www.influxdata.com/products/influxdb-overview) while [Kapacitor](https://www.influxdata.com/time-series-platform/kapacitor) reads the values and send emails when a defined alert is triggered.

== Alerts Included:

* *High CPU*: Measures the total CPU usage on any of the cluster nodes. Threshold: Warning 75%, Critical 90%

* *High Memory*: Measures the memory consumption on any of the cluster nodes. Threshold: Warning 75%, Critical 90%

* *Filesystem Usage*: Measures the file system usage. Threshold: Warning 80%, Critical 90%.

* *Kubernetes Node Status*: Check the kubernetes status for the nodes. Threshold: When kubernetes report a node is _NotReady_.

* *Etcd Latency*: Measures the latency between nodes. Latency might affect `etcd` performance (`etcd` is a database storing the kubernetes state). Threshold: Warning 521, Critical 1024.

* *Systemd health*: Checks if the `systemd` slice (where gravity is running) is not healthy. Threshold: When gravity or the child systems are down (`docker`, `etcd`, `kube-proxy`, `kube-kubelet`, `planet-agent`, `dnsmasq`, `flanneld`, etc.)

* *Influxdb Healthcheck Status*: Checks the health of `Influxdb` (where the metrics for monitoring are stored). Threshold: When there is no connection to Influxdb.

* *Networking Configuration*: Check OS networking flags status. Threshold: When `ip_forward` or `br_netfilter` flags are disabled.

* *Node Uptime*: Checks if the node is online. Threshold: When the node is down for more than 5 minutes.

* *Etcd Health*: Check the status of `etcd`. Threshold: When `etcd` is down or not healthy.

* *Docker Status*: Check docker service is running in each node. Threshold: When docker service is not running.

* *Backup Failing*: Check the result of a backup operation. Threshold: When the backup operation fails.

* *Stolon Replication Lag*: Check if a `Postgres` replica is out of synch. Threshold: When a replica is more than 1800 seconds behind.

== Accessing Alert Definitions

Alerts are defined in 

. From OpsCenter, go to the _Configuration_ panel.
. Select the _monitoring_ namespace.
. Select the _kapacitor-alerts_ configmap.

| There are two alerts that are not defined in this configmap. The backup alert is defined in _backup-status-alert_ and the Cassandra Load alert is defined in _cassandra-load_ configmap. |
| --- |

If you decide to modify an alert, after applying the change in the confimap, you need to restart `Kapacitor`.

== Configuring SMTP to send Alerts

To ensure that alerts work correctly:

* Verify that your SMTP server can send and receive emails using the addresses you configure as the From and To addresses in the following section.
* Verify that your cluster nodes can communicate with your SMTP server. For example, use `telnet` to connect to your SMTP server from one of your cluster nodes:
+
----
telnet my.smtp.server.com 587
Trying XXX.XXX.XXX.XXX...
Connected to my.smtp.server.com.
Escape character is '^]'.
220 my.smtp.server.com ESMTP
^[^]
telnet> quit
Connection closed.
----

== Troubleshooting

If the connection is working, you can check the logs of `kapacitor` to see if there is any other error when seding alerts by email, On Ops Center, you can get the logs in the console ouput by executing: 
+
----
kubectl logs -n monitoring -l component=kapacitor -c kapacitor
----

== Configuring Alerts

. Configure the FROM and TO email addresses:
.. Log in to the Ops Center console, then select Configuration.
.. From the Namespace drop-down, select `monitoring`.
.. From the Config maps drop-down, select `alerting-addresses`.
.. Select the From tab, then enter the FROM email address used for the alert.
.. Select the To tab, then enter the TO email address used for the alert.

. Configure your SMTP email server. Configuring the SMTP server in Access Manager restarts the Anypoint Platform service responsible for initiating the alerts.

== Restarting Kapacitor

[NOTE]
When you change the SMTP settings from Access Management, `kapacitor` is restarted to pick up the settings automatically. If you change an alert definition, or the `alerting-addresses` configmap without changing the SMTP settings from Access Management, `kapacitor` should be restarted manually.

. Open a terminal to one of the master servers
. Execute: `kubectl delete pod -n monitoring -l component=kapacitor`
. Wait for a `kapacitor` pod to be running, you can check executing `kubectl get pod -n monitoring -l component=kapacitor` 

== See Also

* xref:managing-via-the-ops-center.adoc[Ops Center]
