= Allow Addresses for API Platform Proxies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

By default, proxy requests are enabled for the domain name where the platform runs.

== Trusted Domains

Every HTTP request you make to an external resource goes through the API Console Proxy. For security reasons, you must register the domain as an allowed domain in Anypoint Platform. 

By default, proxy requests are blocked for external domains on authenticated requests.

To add a new domain:

1. Log in to Anypoint Platform using an account that has the Organization Administrator permission.

2. In the navigation bar, click *Access Management*.

3. Click *Trusted domains*.

4. Click *Add domain*. 
+
The domain must not match an existing domain,  must not be a domain or subdomain of MuleSoft or Anypoint Platform, and must be written in the format `exampledomain.com`.
NOTE: Regular expressions are not supported.

5. Type the domain name and click *Add domain*.
+
The domain is added to your list of trusted domains. You are redirected to the trusted domains page, where you can edit or delete your domains. If you register a domain on a parent organization, the domain is allowlisted for all of your business groups.

== Authentication 

When using the proxy, there are two authentication modes: 

* Strict Authentication: 
+
(Default) All requests that reach the proxy must be authenticated, which means that user token credentials must be included in the `ms-authorization` header of the request.
+
[WARNING]
If requests to external domains from the Exchange Public Portals go through the API Console Proxy, they fail because no Anypoint user is involved in the call.


* Non-Strict Authentication: 
+
API Console Proxy continues to be unauthenticated but it allows unauthenticated requests. The incoming request must provide either the user's token or a reference to the Organization ID that the request belongs to. The Organization ID must be sent on the `ms-organization-id` header.

To change the authentication method from strict to non-strict, follow these steps:

. Run the following command:
+
----
kubectl patch cm service-env -n api-console-proxy --type merge -p '{"data":{"STRICT_AUTHENTICATION_FF":"false"}}'
----
. Recreate the pods to ensure that each node in the cluster uses the most recent configuration:
+
----
kubectl delete pod -n api-console-proxy -l component=service
----
