= (WILL BE MOVED LATER) Anypoint Platform Private Cloud Edition 3.0 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

*XX xx, 2020*

== New Features and Enhancements

This version of Anypoint Platform Private Cloud Edition (Anypoint Platform for PCE) contains the following features and enhancements:

* Anypoint Platform for PCE features and enhancements

** TBD

* XX features

** TBD


== WIP Deprecations

The following API endpoints were deprecated on April 4th, 2020. Your action is required to avoid potential interruption of applications that integrate with these Anypoint Platform APIs.
 
This API change allows organization administrators to configure multiple Identity Providers (IdPs) for client management.
 
API endpoints approaching deprecation
New API endpoints
accounts/api/organizations/:orgId/provider/clients
accounts/api/organizations/:orgId/clientProviders
accounts/api/organizations/:orgId/clientProviders/:clientProviderId
API endpoints with changed behavior. For clients in third party Identity Providers only.
New API endpoints
GET, POST accounts/api/organizations/:orgId/clients
GET accounts/api/organizations/:orgId/clientProviders/:clientProviderId/clients
GET, POST /exchange/api/v1/organizations/:orgId/applications
GET, PATCH, DELETE accounts/api/organizations/:orgId/clients/:clientId
GET accounts/api/organizations/:orgId/clientProviders/:clientProviderId/clients/:clientId
GET, PATCH, DELETE /exchange/api/v1/organizations/:orgId/applications/:clientId

In addition, the following APIs responses no longer return `client_management` configuration properties.

API endpoints
Deprecated properties
GET accounts/api/organizations/:orgId
properties.identity_management
PUT accounts/api/organizations/:orgId
properties.client_management
GET accounts/api/organizations/:orgId
properties.client_management
GET accounts/api/profile
organization.properties.identity_management
GET accounts/api/me
organization.properties.identity_management
GET accounts/api/organizations/:orgId/users
organization.properties.client_management
GET accounts/api/organizations/:orgId/users/:userId
organization.properties.client_management
GET accounts/api/users/me
organization.properties.identity_management


To prevent disruptive changes, move to new endpoints.

Contact your CSM for assistance.




Add OAS: https://docs.mulesoft.com/release-notes/platform/oas3
OAS3.0 only design phase (Design Center, Exchange). Won't be supported for runtime or management.
s the same support that TODAY is on the platform. Since PCE are cuts of prod environment, the cut is on today and OAS3 support will come to the management plane in the future.
https://mulesoft.slack.com/archives/C27N99AM7/p1596044302424400
https://docs.mulesoft.com/release-notes/platform/oas3















== Installing

Contact MuleSoft professional services prior to installing. MuleSoft professional services must be involved with your installation procedure.

== Upgrade to Anypoint Platform PCE Version 3.0

Contact MuleSoft professional services prior to upgrading. MuleSoft professional services must be involved with your upgrade procedure.

== Software Compatibility

[%header,cols="2*a"]
|===
| Compatible with |Version
| Mule runtime engine | 3.7.x , 3.8.x, 3.9.x, 4.0.x, 4.1.x, 4.2.x, 4.3.0
| API Gateway Runtime | 2.1.x - 2.2.x
| Anypoint Runtime Manager Agent | 1.7 - 1.9.x, 2.1.x
| Anypoint Studio | 6, 7.4
| Infrastructure providers |
* VMWare
* Bare metal
* AWS
|===

== Upgrade Paths
Upgrades from the following PCE versions are supported:

* PCE 2.0.x
* PCE 2.1.x

== Fixed Issues

[%header%autowidth.spread]
|===
| Description
|  
|===

== Known Issues

[%header%autowidth.spread]
|===
| Description | Workaround
|  | 
|===
