= About Anypoint Platform Private Cloud Edition
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Platform Private Cloud Edition enables you to run and manage Mule applications on your local servers, using your required security policies. When running Anypoint Platform Private Cloud Edition, MuleSoft systems do not interact with your data. You configure and run the software and maintain all storage, processing and transmission of data.
// What should be pulled in from https://pce-runbook.kbuild.msap.io/introduction.html???

The Anypoint Platform Private Cloud Edition provides the following application components:

* Runtime Manager: enables you to track and manage your deployed Mule applications
* API Manager: enables you to manage your registered APIs
* Anypoint Exchange: enables your organization to share various assets for reuse across integration projects.

The Anypoint Platform Private Cloud Edition uses Docker and Kubernetes to provide built-in high availability and scalability. You can install the platform without understanding Docker or Kubernetes, but you must understand how they work to manage and troubleshoot the platform.

== See Also

* xref:supported-cluster-config.adoc[Supported Network Topologies]
* xref:prereq-workflow.adoc[Workflow: Install and Verify Prerequisites]
* xref:runtime-manager::index.adoc[Runtime Manager]
* xref:exchange::index.adoc[Anypoint Exchange]
* xref:2.x@api-manager::index.adoc[API Manager]
* https://www.docker.com/[Docker]
* https://kubernetes.io/[Kubernetes]
