= Install Anypoint Platform PCE Using the Command Line Installer
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

After your infrastructure team verifies that the required infrastructure has been correctly installed and configured as described in xref:install-checklist[Product Prerequisites], upload the installation package to all nodes in your environment and select one node from which to run the installation.

[IMPORTANT]
====
Most problems occur from not meeting the minimum system requirements. Before running the installer, ensure that your environment meets the minimum system requirements listed in the xref:install-checklist[Product Prerequisites].
====

The Anypoint Platform Private Cloud Edition (Anypoint Platform PCE) installation package includes specific versions of additional software, such as Docker and Kubernetes. MuleSoft provides patch updates as needed for this additional software.  

== About the Installation Scripts

* Use the Anypoint Platform PCE CLI-based installer when you want to specify all required parameters from the command line.
* The CLI installation uses two scripts:

** `gravity install`: begins the installation and handles intra-server communication during the install. This script also installs the platform on the server. This script is only run on one node.
** `gravity join`: installs the platform on each additional server. This script is run on all nodes except for the node running the `gravity install` script.
* You must run the installation scripts as root to access the necessary privileged ports, and you must run the installation scripts in a single session without interruption. Restarting the installer may cause problems with the installation, which requires you to xref:install-uninstall-reinstall#uninstall-and-reinstall-anypoint-private-cloud[Troubleshoot Anypoint Platform PCE Installation].

== Run the Command Line Installation

. Obtain the `anypoint-2.1.0-installer.tar.gz` archive from your customer success representative.
. Copy the archive to each server node in your cluster. Copy the license file to the installer node.
. Uncompress the gzip archive: 
+
----
tar xvf anypoint-2.1.0-installer.tar.gz
----

. Run the following command on one of the nodes in your cluster:
+
----
sudo ./gravity install --advertise-addr=<installer_IP> --token=<secret token> --cluster=<cluster name> --cloud-provider=generic --flavor=<flavor_name> --license="$(cat license.pem)" --role=<role>
----
+
Use the following values:
+
[%header,cols="2*a"]
|===
|Parameter | Description
|installer_IP | Specifies the IP address used to access the node.
|secret_token | Specifies a secure token used for intra-server communication during the installation. This token must be generated by the same user running the installer. The value of the token can be any numeric value. Just make a note of the value used so that you can provide this value on the commands used on the other nodes in the cluster.  
|cluster_name | Defines the name of your cluster. This can be anything that you choose. Just make a note of the value so that you can provide this value on the commands used on the other nodes in the cluster.
|flavor_name | Specifies the number of nodes in your cluster. Valid values are: `one`, `three`, and `six`.
|role | Specifies the role of the server where you are running the command. Valid values are:

* `general_node` for all nodes in a 3-node configuration
* `app_node` for the installation node and 2 other nodes in a 6-node configuration
* `data_node` for the remaining 3 nodes in a 6-node configuration
|===

. Run the following command on all remaining nodes after the installer node indicates that it is waiting for the other nodes to join. Otherwise, an error is displayed by the nodes trying to join.
+
Use the same secret token value that you provided in the previous command.
+
----
sudo ./gravity join <installer_IP> --advertise-addr=<node_IP> --token=<secret_token> --role=<role> --cloud-provider=generic
----
+
Each of the nodes joins the cluster created by the `./gravity install` command.
+
[WARNING]
If you are running the above command using `ssh` ensure the session does not time out during installation or the installer fails.
Using `nohup` and `&` at the end, e.g. `sudo nohup ./gravity ...rest of command... &` will causes the process to start in the background and continue running if your SSH session expires.
Using `screen` or `tmux` is another alternative to keep a process running if your ssh-session ends.
. Wait for the `./gravity install` and `./gravity join` commands to complete. This can take some time, and you will not receive progress updates during the installation. 

. From the node where you ran `./gravity install`, enter the gravity shell:
+
----
sudo gravity enter
----

. Create the Ops Center and the Anypoint Platform users by running the following command in the gravity shell.
+
[NOTE]
Replace the `email`, `name`, and `password` parameters with the corresponding values for your environment. These are the credentials that a system administrator uses to manage the system.
+
----
curl -X POST http://bandwagon-mulesoft.default.svc.cluster.local/api/complete -H "Content-Type:application/json" -d '{"organization": "Test Org", "email": "username@mulesoft.com", "name": "username", "password": "my_password", "support": false, "nfsServer": "NFS_SERVER_HOST", "nfsPath": "NFS_SERVER_PATH", "platformDns": "PLATFORM_DNS"}'
----

== See Also

* xref:config-workflow.adoc[Post-installation Tasks]
