= Anypoint Private Cloud Installers
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

After your infrastructure team verifies that the required infrastructure has been correctly installed and configured, and you have obtained the necessary information described in xref:prereq-workflow.adoc[Installation Prerequisites], upload the installation package to all nodes in your environment and select one node from which to run the installation. You can then install Anypoint Platform Private Cloud Edition using one of the following installers. 

There are two ways to install Anypoint Private Cloud Edition:

* Using the GUI installer.
* Using the CLI installer.

The GUI based installer requires you to open extra ports and a web browser to access the pages.
The GUI installer is interactive and walks you through a set of wizard pages that enable you to specify configuration options.

The CLI installer does not require human interaction using a web browser and is useful for automation.

[NOTE]
====

- The Anypoint Private Cloud Edition installation package includes specific versions of additional software, such as Docker and Kubernetes. MuleSoft provides patch updates as needed for this additional software. 
- You must run the installer as root to access the necessary privileged ports. 
====

[IMPORTANT]
Most problems occur from not following the minimum system requirements. Make sure that your system meets the minimum system requirements and that you have gathered all information listed in the installation checklist.

== See Also

* xref:install-installer.adoc[To Install using the GUI-based installer]
* xref:install-auto-install.adoc[To Install using the CLI-based installer]
