= Install Anypoint Private Cloud using the GUI Installer
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

After your infrastructure team verifies that the required infrastructure has been correctly installed and configured as described in xref:install-checklist[Product Prerequisites], upload the installation package to all nodes in your environment and select one node from which to run the installation.

[IMPORTANT]
====
Most problems occur from not meeting the minimum system requirements. Before running the installer, ensure that your environment meets the minimum system requirements listed in the xref:install-checklist[Product Prerequisites].

You must have root access (permission to run the `sudo` command) on all servers in your environment and run the installer or upgrade tool as root to access specific privileged ports.
====

The Anypoint Private Cloud installation package includes specific versions of additional software, such as Docker and Kubernetes. MuleSoft provides patch updates as needed for this additional software.

== About the GUI Installer

* The GUI installer provides a wizard that walks you through the Anypoint Platform Private Cloud installation process. It enables you to specify configuration options, but it also requires you to open port 61009 and a web browser to access the pages.
* The GUI installer automatically validates requirements for disk space, disk speed, network speed and operating system version. 

== Run the GUI Installation
You must run the installer as root to access the necessary privileged ports, and you must run the installer in a single session without interruption. Restarting the installer may cause problems with the installation, which requires you to xref:install-uninstall-reinstallxref:install-uninstall-reinstall#uninstall-and-reinstall-anypoint-private-cloud[Troubleshoot Anypoint Private Cloud Installation].

. Obtain the `anypoint-2.0.0-installer.tar.gz` archive from your customer success representative.
. Copy the archive and the license file to the installer node.
. Uncompress the gzip archive:
+
----
tar xvf anypoint-2.0.0-installer.tar.gz
----

. From the location where you unzipped the archive, run the following command:
+
----
./install
----
+

. Select the IP address you want to use and confirm.
. When requested, provide an install token. The value of the token can be any numeric value. Just make a note of the value used so that you can provide this value on the commands used on the other nodes in the cluster.
+
Based on your selection, the installer displays a message similar to the following:
+
----
OPEN THIS IN BROWSER: https://{HOST}:61009/web/installer/new/gravitational.io/anypoint/{VERSION}?install_token={TOKEN}
----
+
The installer runs on an internal IP that you can use to access from within your network. To access the URL from outside the network you must replace the `HOST` hostname in the previous URL with a public IP address.
. Open this URL in a browser.
+
After launching the installation wizard, perform the following steps to install Anypoint Platform Private Cloud.

. Enter your Anypoint Platform license key, then click *Continue*.
+
You must obtain the license key from your MuleSoft account representative. After applying a new license, it may take time for the installer to recognize the license.

. Enter a name for your cluster deployment.
+
This name should be unique to your company. For example: `anypoint.yourcompany`. The name you provide here does not change the network address or organization name in Anypoint Platform.

. Choose a provider, then click Continue.

. Using the slider, select the number of server nodes you want to create.
+
The following configurations are supported:
+
	* 3-node configuration: installs and registers all servers as *General Purpose Nodes*.
	* 6-node configuration: installs and registers three nodes as *App-only* and three nodes as *Data Store*.
+
Depending on the number of nodes you select, the installer displays one or more `curl` commands.

. Run the `curl` command from the command line of each node in your installation.
+
[WARNING]
If you run the commands from an SSH session, ensure the session does not time out during installation or the installer will fail. Using `nohup` and `&` at the end, e.g. `sudo nohup bash &` will make the process to start in the background and will keep running if your ssh session expires.
Using `screen` or `tmux` is another alternative that keeps you process running if your ssh-session ends.
+
If you are running a 3-node configuration, you must run the same command on each server in your environment. If you are running a 6-node configuration, you must run different `curl` commands on the app and data nodes.
+
You must have administrator privileges to run this command. The command should have the following structure, but varies depending on the selected installation flavor you select and the type of the node:
+
----
curl -s --tlsv1.2 --insecure "https://{HOST}:443/t/{TOKEN}/node" | sudo bash
----
+
After running the `curl` command on a node, the node appears in the installer UI.

. Select an IP address from the drop-down list.
+
This IP address is used to communicate within the cluster.

. Choose your Docker device from the drop-down list, or manually specify the path. 
+
This is the device Docker uses for volume management.

. Enter the location of the Application Data device.
+
This is the location of the databases and object stores. By default, this location is `/var/lib/data`.

. Click Verify, to ensure that each of your servers meets the minimum disk and system requirements.
+
This takes a few minutes to complete. If your system meets all requirements, the installer displays a green check mark. If your system does not meet all requirements, an error message that describes the problem is displayed and the installation is paused. This allows you to fix the problem and then continue the installation.

. After all nodes are visible and configured, click *Start Installation*.
+
The installer passes through several different stages. Wait for this process to finish.

. Enter the following information about your organization, Anypoint Platform administrator, and NFS server:
+
* Organization name
+
Platform users access their accounts based on the organization name that you provide here or a business group within it.
* Administrator email
* Administrator username
* Administrator password
* Platform DNS
* NFS server DNS
* NFS server path

== See Also

* xref:config-workflow.adoc[Post-installation Tasks]
