= Installation Workflow

== Install Anypoint Platform Private Cloud Edition (Anypoint Platform PCE)

To install Anypoint Platform PCE, MuleSoft professional services must be involved throughout the installation process. Prior to installation, have your infrastructure team verify that the required infrastructure is correctly installed and configured as described in xref:install-checklist.adoc[Product Prerequisites]. 

== Install Anypoint Monitoring and Anypoint Visualizer

After installing Anypoint Platform PCE, contact your customer success representative to enable Anypoint Monitoring and Anypoint Visualizer. After they are enabled, you must install the agent for each of these product components. See xref:monitoring::am-installing[Monitor Hybrid Runtimes] and xref:visualizer::setup.adoc[Set up Anypoint Visualizer].

[NOTE]
Multi-instance operation of On-Premises Anypoint Runtime Manager is available only if you purchase Anypoint Platform Base Subscription, On-premises Management, API Manager and API Analytics, and Platinum Subscription all together.
