= Uninstall Anypoint Platform Private Cloud
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

If you encounter problems during installation, you can uninstall. Before beginning a new installation, ensure that your environment meets all system requirements listed in the xref:install-checklist[Product Prerequisites], and that all remnants of the original installation have been removed by performing the following commands on all nodes:

. Uninstall Gravity
+
----
# The order of the following steps is important!
# Perform each step in order as described.

# Remove installed system components.
sudo gravity system uninstall --confirm

# Unmount all Anypoint mounts.
sudo umount /var/lib/gravity/planet/etcd
sudo umount /var/lib/gravity/planet/docker
sudo umount /var/lib/gravity
sudo umount /var/lib/data

# Remount and clear platform data.
sudo mount /var/lib/gravity
sudo rm -rf /var/lib/gravity/*

# Remount and clear platform data.
sudo mkdir -p /var/lib/gravity/planet/etcd
sudo mount /var/lib/gravity/planet/etcd
sudo rm -rf /var/lib/gravity/planet/etcd/*

# Remount and clear docker data.
sudo mkdir -p /var/lib/gravity/planet/docker
sudo mount /var/lib/gravity/planet/docker
sudo rm -rf /var/lib/gravity/planet/docker/*

# Remount and clear application data.
sudo mount /var/lib/data
sudo rm -rf /var/lib/data/*
----

. Purge IPTABLES
+
----
# List iptables.
sudo iptables -L -n -v

# Delete any entries.
sudo iptables -F
sudo iptables -X

# Flush nat IP table.
sudo iptables -t nat -F
sudo iptables -t nat -X

# Flush filter IP table.
sudo iptables -t filter -F
sudo iptables -t filter -X

# Verify that iptables are clean
iptables-save

# Persist current iptables state for a server restart
iptables-save > /etc/sysconfig/iptables
----

. Restart the server
+
----
reboot
----

. Verify the requirements are met after the server restart.
. Depending on the state of the full or partial install that you are replacing, the previous commands might not 
completely return the system to an installable state. Before beginning reinstallation, ensure that your system 
still meets all prerequisites listed in the xref:install-checklist[Product Prerequisites] are met.

== See Also

* xref:install-workflow.adoc[Install Anypoint Platform Private Cloud]
* xref:install-installer.adoc[Run the GUI Installer]
* xref:install-auto-install.adoc[Run the CLI Installer]
