= Configuring an External Identity Provider in Anypoint Platform PCE
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: demo-ldap-server.adoc

Anypoint Platform Private Cloud Edition (Anypoint Platform PCE) requires an external identity provider. All users must be registered via external identity except the admin you register in the installation wizard. The following external identity providers are supported:

* xref:access-management::conf-ldap-private-cloud-task.adoc[Configuring LDAP in Anypoint Platform PCE]
* xref:access-management::conf-client-mgmt-pf-task.adoc[Configuring Ping Federate]
* xref:access-management::managing-users.adoc[Configuring SAML]
* xref:access-management::conf-openid-connect-task.adoc[Configuring OpenID Connect]

For troubleshooting information, see https://help.salesforce.com/s/articleView?id=001114931&type=1[Anypoint Platform Single Sign-On (SSO) using OpenID Connect (OIDC) Troubleshooting Guide].

== See Also

* xref:config-workflow.adoc[]
