= Perform Additional Installation Tasks
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

There are some additional installation steps that you may need to perform after installing Anypoint Platform Private Cloud Edition.

== Provide Platform IP or Domain

In order for Mule to communicate with your instance of Anypoint Platform, you must provide the DNS or IP address that exposes your instance of Anypoint Platform to the local network. See xref:access-management-dns.adoc[Configure DNS].

== TLS Certificate

To use Anypoint Platform, you must provide TLS credentials. You can upload a certificate through the Anypoint Platform UI. This certificate must be trusted by every machine connected to the platform, including Mule runtime engines. See xref:access-management-security.adoc[Set Certificates] for more information.

== Configure Log Forwarding

[NOTE]
====
This information is specific to forwarding log data from Anypoint Platform itself. For instructions on how to forward log data from the Mule servers and applications that run on Anypoint Platform, see xref:runtime-manager::sending-data-from-arm-to-external-analytics-software.adoc[Sending Data from Runtime Manager to External Analytics Software].
====


Anypoint Platform uses `rsyslog` to handle logging. To forward these logs to remote hosts, you must configure log forwarding in the Ops Center.

See xref:managing-via-the-ops-center.adoc#configure-log-forwarding[Configure Log Forwarding] for detailed steps on how to do this on the Ops Center.


[NOTE]
You must forward logs to a 3rd-party log solution like Splunk. Sending data to cloud-based log solutions such as Splunk Cloud is not supported.


== Set up SMTP

To handle e-mail alerts for both Runtime Manager and API Manager, you must have an SMTP server configured on your network. You must direct your local installation of Anypoint Platform to this server from the Access Management panel. See xref:access-management-SMTP.adoc[Configure SMTP].

== Use Third Party Authentication

Users can log in to Anypoint Platform using third-party authentication tools. See xref:access-management::external-identity-index.adoc[External Identity] to configure third-party access for each of the available options. The following providers are supported:

* xref:install-config-ldap-pce.adoc[Configure LDAP]
* xref:access-management::conf-client-mgmt-pf-task.adoc[Configure Ping Federate]
* xref:access-management::managing-users.adoc[Configure SAML]
* xref:access-management::conf-client-mgmt-openam-task.adoc[OpenAM]

In the current version of Private Cloud Edition, all users must be registered via external identity, except the admin you register in the installation wizard.

== Add a Custom Disclaimer Message

You can add a custom message to your login page, which all users in your organization will see every time they log in.

== Post Installation

Now that your installation is complete, your instance of Anypoint Platform is ready to use. Users registered in your external identity service should have access to your Anypoint platform xref:access-management::organization.adoc[organization]. As an admin, you can add xref:access-management::roles.adoc[roles] to these users. 

You can also xref:runtime-manager::managing-servers.adoc[register servers] so that you can then xref:runtime-manager::deploying-to-your-own-servers.adoc[deploy to them], and so on.

Mule app developers in your organization who create Mule apps through the xref:6@studio::index.adoc[Anypoint Studio] IDE must set up their editors so the Mule apps interface with your locally installed Anypoint Platform (instead of the default cloud Anypoint Platform). See xref:6@studio::setting-up-your-development-environment.adoc#enable-on-premises-setup[Enable on-premises Setup].

See xref:managing-via-the-ops-center.adoc[Manage Anypoint Platform Private Cloud Edition Using Ops Center] to add or remove servers from the Anypoint Platform cluster as well as other changes you want to make after installation.

[[registering_servers]]
== Registering Servers

Before registering a server, you must configure Mule to trust the TLS certificates you configured:

1. Get the public certificate for you server.
2. Add the certificate to the trustore of the JVM you are using for the Mule runtime.

Example:

----
$ keytool -printcert -sslserver $ANYPOINT_DNS:443 -rfc > /tmp/anypoint.crt
$ keytool -importcert -alias anypoint.my-company -keystore /etc/ssl/certs/java/cacerts -storepass changeit -file /tmp/anypoint.crt
----

In this example, $ANYPOINT_DNS should be set to your DNS for Anypoint Platform Private Cloud Edition.
Replace the location and password for your JVM's trustore for your environment.


== Uploading Custom Policies and Publishing Assets to Exchange Using the Maven Client

There are differences differences between Anypoint Private Cloud Edition and the cloud version of Anypoint Platform you need to consider when uploading custom policies and publishing assets to Exchange using the Maven Client.
See the corresponding documentation for the cloud version of Anypoint Platform for details. 

* xref:2.0@api-manager::custom-policy-getting-started.adoc[Getting started with Custom Policies development],
* xref:2.0@api-manager::custom-policy-uploading-to-exchange.adoc[Uploading Custom Policies]
* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/exchange-maven-facade-api-http/[Maven facade API].

1. Add the server and repository sections in the `settings.xml` file to set up the archetype for your project: 
+
This snippet shows the relevant sections:
[source,xml,linenums]
+
----
    ...
    <server>
       <id>apce-repository</id>
       <username>myusername</username>
       <password>mypassword</password>
    </server>
    ...
    <repository>
       <id>apce-repository</id>
       <name>Anypoint PCE Repository</name>
       <url>https://${ANYPOINT_DNS}/exchange/maven</url>
    </repository>
    ...
----
+
In the examples below, ${ANYPOINT_DNS} is set to your DNS for Anypoint Platform Private Cloud Edition. The `username` and `password` must correspond with your installation.

2. Generate the archetype:
+
Follow the standard process: xref:2.0@api-manager::custom-policy-getting-started.adoc[Getting started with Custom Policies development].
For example:
+
----
mvn -Parchetype-repository archetype:generate \
-DarchetypeGroupId=org.mule.tools \
-DarchetypeArtifactId=api-gateway-custom-policy-archetype \
-DarchetypeVersion=1.0.0 \
-DgroupId=${orgId} \
-DartifactId=${policyName} \
-Dversion=1.0.0-SNAPSHOT \
-Dpackage=mule-policy
----

3. Replace the `exchange.url` in the `pom.xml` file.
By default, `exchange.url` points to the cloud version of Anypoint Platform. `maven.anypoint.mulesoft.com` must point to PCE endpoint:
+
----
<exchange.url>https://${ANYPOINT_DNS}/exchange/maven/api/v1/organizations/${orgId}/maven</exchange.url>
----
+
The `repositoryId` must match the one you configured for Maven in the `settings.xml` file.

4. Package the custom policy.
+
Follow the same process as documented for the cloud version of Anypoint Platform in xref:api-manager::custom-policy-packaging-policy.adoc[Packaging a Custom Policy].

5. Upload the custom policy.
+
Follow the same process as documented for the cloud version of Anypoint Platform in xref:api-manager::custom-policy-uploading-to-exchange.adoc[Uploading a Custom Policy to Exchange].
+
If you receive an error similar to:
+
----
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project ${policyName}:
Failed to retrieve remote metadata ${groupId}:${policyName}:1.0.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata ${orgId}:${policyName}:1.0.0-SNAPSHOT/maven-metadata.xml from/to exchange-server (https://${ANYPOINT_DNS}/exchange/maven/api/v1/organizations/${orgId}/maven): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
----
+
It means the certificate of the platform is not trusted by the local Maven. As in <<registering_servers,Registering Servers>> the solution is to
trust the certificate in the environment where Maven is running.
Example:
+
----
keytool -printcert -sslserver ${ANYPOINT_DNS}:443 -rfc > /tmp/anypoint.crt
keytool -importcert -alias my-company.com -keystore /etc/ssl/certs/java/cacerts -storepass changeit -file /tmp/anypoint.crt
----
+
In this example, $ANYPOINT_DNS is set to your DNS for Anypoint Platform Private Cloud Edition. Replace the location and password for your JVM’s trustore for your environment.

Verify your policy was uploaded by visiting https://${ANYPOINT_DNS}/exchange/?type=policy or https://${ANYPOINT_DNS}/exchange/${orgID}/${artifactId}/ directly.

For an API managed by Mule 4 or above, the policy appears in the *Apply Policy* dialog.

== See Also

* xref:backup-and-disaster-recovery.adoc[Backup and Recovery].
* xref:runtime-manager::managing-servers.adoc[About Servers, Server Groups, and Clusters].
* xref:2.0@api-manager::custom-policy-uploading-to-exchange.adoc[Uploading Custom Policies].
* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/exchange-maven-facade-api-http/[Maven facade API].
