= Anypoint Private Cloud Installers
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

There are two ways to install Anypoint Private Cloud Edition:

* Using a GUI installer.
* Using the CLI.

The GUI based installer requires you to open extra ports and a web browser to access the pages.
The installer is interactive and walks you through a set of wizard pages that enable you to specify configuration options.

The CLI installer does not require human interaction using a web browser and is useful for automation.

NOTE: The installation package includes everything required for Anypoint Private Cloud Edition installation, 
including specific versions of additional software, such as Docker and Kubernetes. MuleSoft provides updates as 
needed for the additional software with Anypoint Private Cloud Edition patches.  

== See Also

* xref:install-installer.adoc[To Install using the GUI-based installer]
* xref:install-auto-install.adoc[To Install using the CLI-based installer]
