= Set up a Load Balancer for Anypoint Platform Private Cloud Edition
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Platform Private Cloud Edition must run in a production environment with multiple servers. To distribute traffic among servers and to restrict access to specific ports, you must install and configure a load balancer. 

You can use any load balancer, including NGINX, but NGINX is not required.

[NOTE]
If using the xref:prereq-aws-terraform.adoc[AWS Provisioner for Anypoint Private Cloud Edition], skip this section. An Amazon ELB is created during installation with the required configuration.

You can configure your load balancer to use any method for distributing client requests, but in most contexts a round robin strategy is ideal. The load balancer should be accessible through an IP address that is available to all machines in your network.

Your load balancer must route the following TCP ports:

[%header%autowidth.spread]
|===
|Load Balancer Port |Instance Port | Internal Usage
|`80` | `30080`  | HTTP redirects to HTTPs.
|`443` | `30443` | HTTPS port
|`8889` | `30889` | WebSocket Port for Runtimes to connect
|`9500` | `32009` | Ops Center Access Port
|===


In each case, your load balancer must listen on the Load Balancer Port and redirect incoming requests to the Instance Port. Your Anypoint Platform installation includes an internal NGINX server that listens on each of the configured instance ports, then performs the action listed in the Internal Usage column.

Your load balancer should poll the address `HTTP:10248/healthz` to run a health check on your platform servers and confirm that they are accessible.


[NOTE]
Do not configure SSL credentials in your load balancer. TLS termination is handled by the platform with the certificates configured using Access Management. See xref:install-add-tasks.adoc[To Perform Additional Installation Tasks].

== Implement a Load Balancer using Nginx

. Enable stream block in your `/etc/nginx/nginx.conf` file, by referencing all the configuration properties defined in `/etc/nginx/stream.d/*`. You can achieve that by adding the following:
+
[source,json,linenums]
----
stream {
   include /etc/nginx/stream.d/*.conf;
}
----

. Delete the `default.conf` file from `/etc/nginx/conf.d`
. Create a folder named `/etc/nginx/stream.d` and in it create a file named `onprem.conf`
. Paste the following content in `onprem.conf`
+
[source,json,linenums]
----
server {
   listen 80;
   proxy_pass 0.0.0.0:30080;
}

server {
   listen 443;
   proxy_pass 0.0.0.0:30443;
}

server {
   listen 8889;
   proxy_pass 0.0.0.0:30889;
}

server {
   listen 9500;
   proxy_pass 0.0.0.0:32009;
}

server {
   listen 9501;
   proxy_pass 0.0.0.0:30083;
}
----

. Enable the default ports on SELinux before starting the NGINX. Run the following commands one by one:
+
----
semanage port -a -t http_port_t  -p tcp 8889
semanage port -a -t http_port_t  -p tcp 9500
semanage port -a -t http_port_t  -p tcp 9501
----

. Start NGINX:
+
----
service nginx restart
----

== See Also
* https://www.nginx.com/[Nginx]
