= Installing Anypoint Platform PCE on OpenShift

Before installing Anypoint Platform Private Cloud Edition (Anypoint Platform PCE) on OpenShift, you must configure Security Context Constraints (SCC) to grant the required permissions for pods and create roles for Prometheus, allowing it to collect metrics from the services. After these configurations are complete, proceed with installing Anypoint Platform PCE.

[NOTE]
You must have an operational OpenShift cluster prior installing Anypoint Platform PCE. If you do not have one set up, refer to the OpenShift documentation for setup instructions.

== Configure the Openshift Environment

To configure the OpenShift Environment, configure Security Context Constraints (SCC) and roles for Prometheus.

=== Configure Security Context Constraints (SCC)

The following snippet contains the SCC configuration:

[source,yaml]
----
include::../assets/src/openshift/openshift-scc.yaml[]
----

Save this file as `openshift-scc.yaml` and apply it to the OpenShift cluster:

[source]
----
oc apply -f openshift-scc.yaml
----

=== Configure Roles for Prometheus

Prometheus requires specific roles to collect metrics from Anypoint Platform PCE services. The following snippet provides the necessary roles configuration:

[source,yaml]
----
include::../assets/src/openshift/openshift-monitoring.yaml[]
----

Save this file as `openshift-monitoring.yaml` and apply it to the OpenShift cluster:

[source]
----
oc apply -f openshift-monitoring.yaml
----

== Install Anypoint Platform PCE on OpenShift

The following snippet provides an example installation manifest for deploying Anypoint Platform PCE on an OpenShift cluster:

[source,yaml]
----
include::../assets/src/openshift/openshift-example.yaml[]
----

Note the `monitoringAppConfiguratio` section in the snippet. This section disables the monitoring stack for Anypoint Platform PCE and enables only the Grafana application. It is recommended to disable the monitoring stack because OpenShift includes Prometheus by default. Enable Grafana and configure its datasource to connect to Prometheus.

To obtain the token for connecting to Prometheus, run this comand:

[source]
----
oc create token prometheus-k8s -n openshift-monitoring --duration=87600h
----

After completing the installation, run the following commands to allow Prometheus in OpenShift to collect metrics from platform services:

[source]
----
oc label namespace default openshift.io/cluster-monitoring="true" --overwrite
oc label namespace pce openshift.io/cluster-monitoring="true" --overwrite
----

== See Also

* xref:install-worflow.adoc[]
* xref:install-checklist.adoc[]