= Installing or Upgrading Anypoint Platform Private Cloud Edition (Anypoint Platform PCE)
:page-aliases: prereq-gravity-check.adoc

The process to install Anypoint Platform Private Cloud Edition (Anypoint Platform PCE), consist of the following steps:

. Obtaining your Anypoint PCE installation distribution
. Setting up and verifying your infrastructure
. Performing a pre-installation verification
. Installing/Upgrading Anypoint Platform PCE

[NOTE]
Contract Mulesoft Processional Services or your Anypoint PCE Certified Partner to obtain your Anypoint PCE installation distribution and before performing the pre-installation verification and installation or upgrade of the Anypoint PCE Platform to ensure they are involved in these procedures.

[NOTE]
To install Anypoint Platform PCE on OpenShift, see xref:install-openshift.adoc[Installing Anypoint Platform PCE on OpenShift].


== Set Up and Verify your Infrastructure

Before you install Anypoint Platform PCE, ensure your infrastructure team installed and configured correctly the infrastructure for your organization following the requirements as described in xref:install-checklist.adoc[Anypoint Platform PCE Prerequisites].

== Perform a Pre-installation Verification

To perform the pre-installation healthcheck verification for the Kubernetes (K8s) cluster, follow these steps:

. Confirm your Kubernetes cluster version is 1.34.x or 1.33.x.
. Create an `input.yaml` file using this template and update it with your environment details:

[source,json,linenums]
----
# Container Registry configuration to upload PCE images
containerRegistry:
  endpoint: "" # Container Registry Endpoint
  username: "" # Provide either Username/Password OR Certificate to authenticate with container registry
  password: ""
  certificate: "/etc/registry/certificate/ca.crt"
  subproject: "mulesoft" # Container registry subproject under which all the PCE images will be part of.
  tlsSkipVerify: True  # True or False.
# Platform configuration using CSI driver for filesystem access
platformConfiguration:
  platformDNS: ""
  fileSystemCsiDriverName: "" # CSI driver name (e.g., nfs.csi.k8s.io, efs.csi.aws.com)
  # Provide NFS DNS and path (not required if using EFS CSI Driver)
  # fileSystemDNS: ""
  # fileSystemPath: ""
  # Provide individual NFS volume handles (all 4 are required if using EFS CSI Driver. You'll need to create 4 access points pointing to the same dir in the EFS)
  fileSystemWcCsiVolumeHandle: "" # CSI volume handle for wc filesystem. E.g.: fs-0835b0d1eb7588eb1::fsap-03f6c68563ceb5acf
  fileSystem01CsiVolumeHandle: "" # CSI volume handle for 01 filesystem
  fileSystemBareCsiVolumeHandle: "" # CSI volume handle for bare filesystem
  fileSystemBackupRestoreCsiVolumeHandle: "" # CSI volume handle for backup-restore filesystem
  platformCertificate: /path/to/platform/certificate/cert.crt
  platformCertificateKey: path/to/platform/certificate/cert.key
  firstUserAccount:
    organizationName: 'Test Org'
    username: 'username'
    email: 'username@mulesoft.com'
    password: '<a-valid-password>'
# Storage class configuration for persistent data services
storageConfiguration:
  pceobjectstore:
    type: "persistentVolumeClaim"
    storageClass: "<storage-class-name>"
    controlPlaneSize: "10Gi" # Optional. Defaults to 10Gi
    volumeSize: "100Gi" # Optional. Defaults to 100Gi
    volumeIndexSize: "10Gi" # Optional. Defaults to 10Gi
  stolon:
    type: "persistentVolumeClaim"
    storageClass: "<storage-class-name>"
    size: "100Gi" # Optional. Defaults to 100Gi
  backupRestoreTmp:
    storageClass: "<storage-class-name>" # Storage class for backup/restore temporary storage
# Configuration options for monitoring stack
monitoringAppConfiguration:
  monitoringStack:
    enabled:  True # Defaults to True. Must be set to False for Openshift clusters.
#    values: | # Optional. If not provided, the default values will be used.
#      prometheus:
#        prometheusSpec:
#          storageSpec:
#            volumeClaimTemplate:
#              spec:
#                storageClassName: 'local-path',
#                accessModes: ["ReadWriteOnce"]
#                resources:
#                  requests:
#                    storage: 50Gi

## The following section is used to configure Grafana for an Openshift cluster. It is recommended to disable the monitoring stack as OpenShift includes Prometheus by default.
#  grafana:
#    enabled: False # Defaults to False.
#    values: |
#      datasources:
#        datasources.yaml:
#          apiVersion: 1
#          datasources:
#          - name: Prometheus
#            type: prometheus
#            url: https://prometheus-k8s.openshift-monitoring.svc:9091
#            access: proxy
#            isDefault: true
#            jsonData:
#              tlsSkipVerify: true
#              httpHeaderName1: 'Authorization'
#            secureJsonData:
#              httpHeaderValue1: 'Bearer <Token>'
----
[start=3]
. Obtain the `license.lic` file from the MuleSoft Professional Services team.
. Set the `KUBECONFIG` environment variable to the path to the `kubeconfig` file of the cluster.
. Verify that the cluster satisfies the prerequisites by running the following command against your `input.yaml` file and the `license.lic` file:
+
`./pcectl pre-install-check --input-file/path/to/input.yaml --license-file /path/to/license.lic`

[start=6]
. For Anypoint Platform PCE workload to be scheduled on designated nodes, apply the following labels to all worker nodes:
* `mulesoft-role=node`
* `redis-role=node`
. Apply the following labels to any three worker nodes. These do not need to be the same three nodes:
* `stolon-keeper=yes`
* `pce-data-nodes=yes`
. (Optional) Apply taints to controlplane nodes to ensure that no Anypoint Platform PCE workload is scheduled on the control plane. This also affects any other workload your organization may want to run on control plane nodes. Consult with your Kubernetes cluster admin to perform this step:
+
`mulesoft.pce/controlplane-node=true:NoSchedule`



== Install Anypoint Platform PCE

After your infrastructure is correctly set up and you performed a pre-installation verification, MuleSoft Professional Services or your Anypoint PCE Certified Partner will assist you with the installation of Anypoint Platform PCE.

To install Anypoint Platform PCE, run this command:

`./pcectl install --input-file /path/to/input.yaml --license-file /path/to/license.lic`

== Upgrade Anypoint Platform PCE 

After you have completed a pre-installation/upgrade verification, MuleSoft Professional Services or your Anypoint PCE Certified Partner will assist you with the upgrade of Anypoint Platform PCE.

To upgrade Anypoint Platform PCE, run this command:

`./pcectl upgrade /path/to/input.yaml --license-file /path/to/license.lic`

== See Also

* xref:install-checklist.adoc[Anypoint Platform PCE Prerequisites].
