= Perform Additional Installation Tasks
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This topic describes additional installation steps that you may need to perform after installing Anypoint Platform Private Cloud Edition.

== Provide Platform IP or Domain

Provide the DNS or IP with which your instance of the Anypoint Platform is exposed to the local network, this is necessary for Mule runtimes to be able to communicate with it. See xref:access-management-dns.adoc[Configure DNS].

== TLS Certificate

To use Anypoint Platform, you must provide TLS credentials. You can upload a certificate through the Anypoint Platform UI. This certificate must be trusted by every machine connected to the platform, including Mule runtimes. See xref:access-management-security.adoc[Set Certificates] for more information.

== Configure Log Forwarding

[NOTE]
This section refers to forwarding log data from Anypoint Platform itself. For instructions on how to forward log data from the Mule servers and applications that run on the platform, see xref:runtime-manager::sending-data-from-arm-to-external-analytics-software.adoc[Sending data from Runtime Manager to External Analytics Software].


Anypoint Platform uses `rsyslog` to handle logging. To forward these logs to remote hosts you must configure this in the Ops Center.

See xref:managing-via-the-ops-center.adoc#configure-log-forwarding[Configure Log Forwarding] for detailed steps on how to do this on the Ops Center.


[NOTE]
You must forward logs to a 3rd-party log solution like Splunk. It's not supported to send data to a cloud-based log solution, like Splunk Cloud.


== Set up SMTP

To handle e-mail alerts for both Runtime Manager and API Manager, you must have an SMTP server configured on your network. You must direct your local installation of Anypoint Platform to this server from the Access Management panel. See xref:access-management-SMTP.adoc[Configure SMTP].

== Use Third Party Authentication

Users can log in to Anypoint Platform using third-party authentication tools. See xref:access-management::external-identity.adoc[External Identity] to configure third-party access for each of the available options. The following providers are supported:

* xref:install-config-ldap-pce.adoc[LDAP]
* xref:access-management::managing-api-clients.adoc#ping-federate[ping federate]
* xref:access-management::managing-users.adoc#instructions-for-saml-configuration[SAML]
* xref:access-management::managing-api-clients.adoc#openam[OpenAM].

In the current version, all users must be registered in the platform via external identity, except the admin you register from the installation wizard.

== Add a Custom Disclaimer Message

You can add a custom message to your login page, that all users in your organization will see every time you log in.

== Post Installation

Now that your installation is complete, your platform is ready for being used. Users registered in your external identity service should have access to your Anypoint platform xref:access-management::organization.adoc[organization]. As an admin you can now add xref:access-management::roles.adoc[roles] to these users. You can also start xref:runtime-manager::managing-servers.adoc[registering servers] so that you can then xref:runtime-manager::deploying-to-your-own-servers.adoc[deploy to them], etc.

The developers of your organization that create Mule apps through the xref:6@studio::index.adoc[Anypoint Studio] IDE should set up their editors so that these interface with your locally installed Anypoint Platform (instead of the default cloud Anypoint Platform). See xref:6@studio::setting-up-your-development-environment.adoc#enable-on-premises-setup[Enable on-premises Setup].

See xref:managing-via-the-ops-center.adoc[Managing via the Ops Center] to add or remove servers from the platform cluster and other changes you may want to carry out after installation.

== Registering Servers

Before registering a server, you must configure Mule runtime to trust the TLS certificates you configured:

1. Get the public certificate for you server.
2. Add the certiticate to the trusture of the JVM you are using for the Mule runtime.

Example:

----
$ keytool -printcert -sslserver $ANYPOINT_DNS:443 -rfc > /tmp/anypoint.crt
$ keytool -importcert -alias anypoint.my-company -keystore /etc/ssl/certs/java/cacerts -storepass changeit -file /tmp/anypoint.crt
----

In this example, $ANYPOINT_DNS should be set to your DNS for Anypoint Platform Private Cloud Edition.
Replace the location and password for your JVM's trustore for your environment.


== Uploading Custom Policies / Publishing Assets to Exchange Using the Maven Client

This section focuses in the differences between Anypoint Private Cloud Edition and the cloud version of Anypoint.
For complete details see the corresponding documentation for xref:2.0@api-manager::custom-policy-getting-started.adoc[Getting started with Custom Policies development],
xref:2.0@api-manager::custom-policy-uploading-to-exchange.adoc[Uploading Custom Policies] and https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/exchange-maven-facade-api-http/[Maven facade API].

1. Configure settings.xml with archtype adding the server section and the repository:
+
This snippet shows the relevant sections:
[source,xml,linenums]
+
----
    ...
    <server>
       <id>apce-repository</id>
       <username>myusername</username>
       <password>mypassword</password>
    </server>
    ...
    <repository>
       <id>apce-repository</id>
       <name>Anypoint PCE Repository</name>
       <url>https://${ANYPOINT_DNS}/exchange/maven</url>
    </repository>
    ...
----
+
In the examples below, ${ANYPOINT_DNS} should be set to your DNS for Anypoint Platform Private Cloud Edition. username and password should correspond with your installation.

2. Generate the archtype
+
Follow the standard process: xref:2.0@api-manager::custom-policy-getting-started.adoc[Getting started with Custom Policies development].
e.g.
+
----
mvn -Parchetype-repository archetype:generate \
-DarchetypeGroupId=org.mule.tools \
-DarchetypeArtifactId=api-gateway-custom-policy-archetype \
-DarchetypeVersion=1.0.0 \
-DgroupId=${orgId} \
-DartifactId=${policyName} \
-Dversion=1.0.0-SNAPSHOT \
-Dpackage=mule-policy
----

3. Replace the exchange.url in the pom.xml file
exchange.url is by default pointing to the Cloud version of Anypoint: maven.anypoint.mulesoft.com must point to PCE endpoint:
+
----
<exchange.url>https://${ANYPOINT_DNS}/exchange/maven/api/v1/organizations/${orgId}/maven</exchange.url>
----
+
Make sure the repositoryId matches the one you configured for maven in settings.xml

4. Package the custom policy
+
Follow the standard process: xref:api-manager::custom-policy-packaging-policy

5. Upload the custom policy
+
Following the standard process: xref:api-manager::custom-policy-uploading-to-exchange
+
If you receive an error simmilar to:
+
----
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project ${policyName}:
Failed to retrieve remote metadata ${groupId}:${policyName}:1.0.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata ${orgId}:${policyName}:1.0.0-SNAPSHOT/maven-metadata.xml from/to exchange-server (https://${ANYPOINT_DNS}/exchange/maven/api/v1/organizations/${orgId}/maven): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
----
+
It means the certificate of the platform is not trusted by the local maven. As in <<Registering Servers>> the solution is to
trust the certificate in the environment where maven is running.
Example:
+
----
keytool -printcert -sslserver ${ANYPOINT_DNS}:443 -rfc > /tmp/anypoint.crt
keytool -importcert -alias my-company.com -keystore /etc/ssl/certs/java/cacerts -storepass changeit -file /tmp/anypoint.crt
----
+
In this example, $ANYPOINT_DNS should be set to your DNS for Anypoint Platform Private Cloud Edition. Replace the location and password for your JVM’s trustore for your environment.

Check your policy was uploaded by visiting https://${ANYPOINT_DNS}/exchange/?type=policy or https://${ANYPOINT_DNS}/exchange/${orgID}/${artifactId}/ directly

For an API managed by Mule 4 or above, the policy will appear in the Apply Policy dialog.

== See Also

* xref:backup-and-disaster-recovery.adoc[Backup and Recovery].
* xref:runtime-manager::managing-servers.adoc[About Servers, Server Groups, and Clusters].
* xref:2.0@api-manager::custom-policy-uploading-to-exchange.adoc[Uploading Custom Policies].
* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/exchange-maven-facade-api-http/[Maven facade API].
