= Managing Anypoint Platform PCE
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: license-influx-update.adoc, ext-analytics-elk.adoc

After your installation is complete, your instance of Anypoint Platform Private Cloud Edition (Anypoint Platform PCE) is ready to use. 

== Users Using Anypoint Platform PCE
Ensure that users registered in your external identity service have access to your Anypoint Platform xref:access-management::organization.adoc[organization].

You can also xref:runtime-manager::managing-servers.adoc[register servers] so that you can then xref:runtime-manager::deploying-to-your-own-servers.adoc[deploy to them], and so on.

== Mule Developers Using Anypoint Studio
Mule app developers in your organization who create Mule apps through the xref:studio::index.adoc[Anypoint Studio] IDE must set up their editors so the Mule apps interface with your locally installed Anypoint Platform rather than the default cloud Anypoint Platform.

== Mule Developers Using Anypoint Code Builder
You can also use Anypoint Code Builder to develop and deploy Mule apps to your Anypoint PCE environment. For more information, see xref:deploy-mule-apps-acb.adoc[Deploying Mule Apps to Anypoint PCE Using Anypoint Code Builder].

== Manage Anypoint Platform PCE

The following topics describe how to manage Anypoint Platform PCE:

* xref:backup-and-disaster-recovery.adoc[Backing up and restoring for Anypoint Platform PCE]
* xref:config-add-proxy-allowlist.adoc[Allowing addresses for API Platform proxies]
* xref:custom-policies.adoc[Uploading custom policies and publish assets to exchange using the Maven client]
* xref:adding-compatible-java-versions-using-the-maven-client.adoc[]
* xref:config-studio.adoc[Configuring Anypoint Studio for Anypoint Platform PCE]
* xref:deploy-mule-apps-acb.adoc[Deploying Mule Apps to Anypoint PCE Using Anypoint Code Builder]
* xref:ext-analytics-elk.adoc[Analyzing Business and API Data Using ELK]
* xref:register-server.adoc[Troubleshooting Mule Runtime Engine Registration]
* xref:restarting-a-node.adoc[Updating Nodes]

== See Also

* xref:install-workflow.adoc[]
* xref:config-workflow.adoc[]
