= Managing Anypoint Private Cloud - WIP
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Now that your installation is complete, your instance of Anypoint Platform is ready to use. Users registered in your external identity service should have access to your Anypoint platform xref:access-management::organization.adoc[organization]. As an admin, you can add xref:access-management::roles.adoc[roles] to these users. 

You can also xref:runtime-manager::managing-servers.adoc[register servers] so that you can then xref:runtime-manager::deploying-to-your-own-servers.adoc[deploy to them], and so on.

Mule app developers in your organization who create Mule apps through the xref:studio::index.adoc[Anypoint Studio] IDE must set up their editors so the Mule apps interface with your locally installed Anypoint Platform (instead of the default cloud Anypoint Platform). 

See xref:managing-via-the-ops-center.adoc[Manage Anypoint Platform Private Cloud Edition Using Ops Center] to add or remove servers from the Anypoint Platform cluster as well as other changes you want to make after installation.

[[registering_servers]]
== Register Servers

Before registering a server, you must configure Mule to trust the TLS certificates you configured:

1. Get the public certificate for you server.
2. Add the certificate to the trustore of the JVM you are using for the Mule runtime.

Example:

----
$ keytool -printcert -sslserver $ANYPOINT_DNS:443 -rfc > /tmp/anypoint.crt
$ keytool -importcert -alias anypoint.my-company -keystore /etc/ssl/certs/java/cacerts -storepass changeit -file /tmp/anypoint.crt
----

In this example, $ANYPOINT_DNS should be set to your DNS for Anypoint Platform Private Cloud Edition.
Replace the location and password for your JVM's trustore for your environment.


== Upload Custom Policies and Publish Assets to Exchange Using the Maven Client

There are differences differences between Anypoint Private Cloud Edition and the cloud version of Anypoint Platform you need to consider when uploading custom policies and publishing assets to Exchange using the Maven Client.
See the corresponding documentation for the cloud version of Anypoint Platform for details. 

* xref:api-manager::custom-policy-getting-started.adoc[Getting started with Custom Policies development],
* xref:api-manager::custom-policy-uploading-to-exchange.adoc[Uploading Custom Policies]
* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/exchange-maven-facade-api-http/[Maven facade API].

1. Add the server and repository sections in the `settings.xml` file to set up the archetype for your project: 
+
This snippet shows the relevant sections:
[source,xml,linenums]
+
----
    ...
    <server>
       <id>apce-repository</id>
       <username>myusername</username>
       <password>mypassword</password>
    </server>
    ...
    <repository>
       <id>apce-repository</id>
       <name>Anypoint PCE Repository</name>
       <url>https://${ANYPOINT_DNS}/exchange/maven</url>
    </repository>
    ...
----
+
In the examples below, ${ANYPOINT_DNS} is set to your DNS for Anypoint Platform Private Cloud Edition. The `username` and `password` must correspond with your installation.

2. Generate the archetype:
+
Follow the standard process: xref:api-manager::custom-policy-getting-started.adoc[Getting started with Custom Policies development].
For example:
+
----
mvn -Parchetype-repository archetype:generate \
-DarchetypeGroupId=org.mule.tools \
-DarchetypeArtifactId=api-gateway-custom-policy-archetype \
-DarchetypeVersion=1.0.0 \
-DgroupId=${orgId} \
-DartifactId=${policyName} \
-Dversion=1.0.0-SNAPSHOT \
-Dpackage=mule-policy
----

3. Replace the `exchange.url` in the `pom.xml` file.
By default, `exchange.url` points to the cloud version of Anypoint Platform. `maven.anypoint.mulesoft.com` must point to PCE endpoint:
+
----
<exchange.url>https://${ANYPOINT_DNS}/exchange/maven/api/v1/organizations/${orgId}/maven</exchange.url>
----
+
The `repositoryId` must match the one you configured for Maven in the `settings.xml` file.

4. Package the custom policy.
+
Follow the same process as documented for the cloud version of Anypoint Platform in xref:api-manager::custom-policy-packaging-policy.adoc[Packaging a Custom Policy].

5. Upload the custom policy.
+
Follow the same process as documented for the cloud version of Anypoint Platform in xref:api-manager::custom-policy-uploading-to-exchange.adoc[Uploading a Custom Policy to Exchange].
+
If you receive an error similar to:
+
----
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project ${policyName}:
Failed to retrieve remote metadata ${groupId}:${policyName}:1.0.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata ${orgId}:${policyName}:1.0.0-SNAPSHOT/maven-metadata.xml from/to exchange-server (https://${ANYPOINT_DNS}/exchange/maven/api/v1/organizations/${orgId}/maven): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
----
+
It means the certificate of the platform is not trusted by the local Maven. As in <<registering_servers,Registering Servers>> the solution is to
trust the certificate in the environment where Maven is running.
Example:
+
----
keytool -printcert -sslserver ${ANYPOINT_DNS}:443 -rfc > /tmp/anypoint.crt
keytool -importcert -alias my-company.com -keystore /etc/ssl/certs/java/cacerts -storepass changeit -file /tmp/anypoint.crt
----
+
In this example, $ANYPOINT_DNS is set to your DNS for Anypoint Platform Private Cloud Edition. Replace the location and password for your JVM’s trustore for your environment.

Verify your policy was uploaded by visiting https://${ANYPOINT_DNS}/exchange/?type=policy or https://${ANYPOINT_DNS}/exchange/${orgID}/${artifactId}/ directly.

For an API managed by Mule 4 or above, the policy appears in the *Apply Policy* dialog.


The following topics describe how to manage Anypoint Private Cloud after installation and configuration:

*** xref:managing-via-the-ops-center.adoc[To Manage Anypoint Platform Private Cloud Edition Using Ops Center]
*** xref:backup-and-disaster-recovery.adoc[To Configure Backup and Restore]
*** xref:ops-center-update-lic.adoc[To Add a Product License Using Ops Center]
*** xref:config-alerts.adoc[To Setup Alerts for CPU and Memory Usage]
*** xref:config-add-proxy-whitelist.adoc[To Add Whitelist Addresses for API Platform Proxies]
*** xref:demo-ldap-server.adoc[To Configure the Demo LDAP Server]
*** xref:ext-analytics-elk.adoc[To Analyze Business and API Data using ELK]
*** xref:restarting-a-node.adoc[Stop, Restart, or Update an Anypoint Platform Private Cloud Edition Node]
