= Software Requirements for Anypoint Private Cloud
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: prereq-verify-software.adoc

To ensure the performance and stability of Anypoint Platform Private Cloud Edition, every node in your Anypoint Platform Private Cloud Edition environment must meet the software requirements described in this topic. 

[IMPORTANT]
Before installing or upgrading, your infrastructure team must review each of the following sections and verify that your environment meets the stated software requirements. If needed, contact your Customer Success Manager for assistance.

== Supported Linux Distributions
The following Linux distributions are supported:

* Red Hat Enterprise Linux (RHEL), versions 7.4.x, 7.5.x, and 7.6

* CentOS, versions 7.4.x, 7.5.x, and 7.6

== SELinux
SELinux is not required, but Anypoint Platform Private Cloud Edition supports the default SELinux profile running 
in strict mode. If your environment uses a custom profile, it must provide an unconstrained user context when 
running the installer. Review any custom profiles with your customer support representative.

== Kernel Modules

On each node, ensure that the following kernel modules are enabled:

* `br_netfilter`
* `ebtable_filter`
* `ip_tables`
* `iptable_filter`
* `iptable_nat`

Verify that each module is loaded using the following command as an example:

----
root$ lsmod | grep br_netfilter
----

Repeat this command for each of the kernel modules above. If this command does not display any output, then the module is not loaded. In this case, load the module using `modprobe`:

----
root$ modprobe br_netfilter
----

To ensure the module is loaded after a reboot:

----
root$ echo 'br_netfilter' > /etc/modules-load.d/br_netfilter.conf
----

Replace `br_netfilter` with the name of the kernel module you are checking.

== Kernel Settings

The following flags must be turned on:

* `net.bridge.bridge-nf-call-iptables=1`
* `net.ipv4.ip_forward=1`
* `fs.may_detach_mounts=1`
* `fs.inotify.max_user_watches=524288`

Ensure that there are no processes on your system that set this flag to false. To set a parameter you can use `sysctl -w`, for example:

----
root$ sysctl -w net.ipv4.ip_forward=1
----

To make the changes permanent for the next reboot, write it to a file under `/etc/sysctl.d`:

----
echo net.ipv4.ip_forward=1 >> /etc/sysctl.d/10-ipv4-forwarding.conf
----

Replace the setting above with the setting you are configuring. Ensure there are no processes or files conflicting with those settings.

== Install Logical Volume Manager 2 (LVM2)

To install and run Anypoint Platform Private Cloud Edition, you must install and use LVM2. LVM2 is a tool that adds a layer of abstraction between your operating system and the disks/partitions it uses. You must have root access to install LVM2.

You can install LVM using Yum. Yum is an open-source command-line package-management utility for Linux operating systems using the RPM Package Manager. Using Yum, you can install LVM through the following command:

----
sudo yum install lvm2
----

== Enable Forwarding When Using firewalld

xref:prereq-network#enable-forwarding-when-using-firewalld[To Enable Forwarding When Using firewalld]

== Synchronize clocks

Ensure that the clocks on all servers are synchronized. Unsynchronized clocks can cause problems with platform communications.

== Uninstall Unsupported Software

The following sections describe software that can cause conflicts with Anypoint Platform Private Cloud Edition. You must uninstall these components before performing Anypoint Platform Private Cloud Edition installation.

=== Docker

Docker should be uninstalled from servers running the Anypoint Platform Private Cloud Edition. The Anypoint Platform installation includes a Docker package officially supported by Kubernetes.

=== Local DNS Servers

Local caching DNS servers listening on port 53 should be removed, e.g. named, dnsmasq, bind or others.


== See Also

* xref:prereq-hardware.adoc[Hardware Requirements for Anypoint Private Cloud]
* xref:prereq-network.adoc[Network Requirements for Anypoint Private Cloud]
* xref:verify-nfs.adoc[NFS Server Requirements for Anypoint Private Cloud]
