= Hardware Requirements for Anypoint Private Cloud
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To ensure the performance and stability of Anypoint Platform Private Cloud Edition, your environment must meet the minimum system requirements described in this topic. Before installing or upgrading, review each of following sections and ensure that your environment meets these requirements.

[WARNING]
If your system does not meet all of the minimum system requirements, you cannot install Anypoint Platform Private Cloud Edition.

Two cluster topologies are supported for Anypoint Platform Private Cloud Edition: 3-nodes and 6-nodes. See xref:supported-cluster-config.adoc[Supported Network Topologies]. The requirements for all nodes are the same.

== Memory and CPU Requirements

[%header%autowidth.spread]
|===
| Component |Requirement
|RAM |32 GB
|CPU |8 Cores
|===

== Disk Size and Performance Requirements

Anypoint Platform Private Cloud Edition has strict minimum size and performance requirements for storage devices used by the platform. All disk drives must meet the following criteria:

* Must have at least 300 MB/sec of throughput.
* Must have high performance capability, even if they are virtual block devices or network attached storage.

For production usage, each node in your configuration must have the following devices and they must meet the stated minimum requirements.

[%header%autowidth.spread]
|===
| Component |Size|Minimum IOPS|Mount Point
|HDD 1 (operating system) |50 GB |500|
|HDD 2 (System data) | 100 GB |1500|/var/lib/gravity
|HDD 3 (Application data)| 250 GB |1500|/var/lib/data
|HDD 4 (Docker) | 100 GB |3000|Not mounted
|HDD 5 (Etcd) | 20 GB |3000|/var/lib/gravity/planet/etcd
|/tmp (installer) | 20 GB |N/A|
|===


The devices should be formatted either as *xfs* or *ext4*. It's recommended to have dedicated devices for each component:

* System data: Stores system configuration and metadata, including databases and packages. As package sizes can be arbitrary large, it is important to estimate the minimum size requirements and allocate enough space as a dedicated device before installation.
* Application data: Stores application configuration and data. The amount of space required should be at least 250 GB, but might vary depending on your specific use case. It is important to estimate the minimum size requirements and allocate enough space as a dedicated device ahead of time.
* Docker: Used by Docker’s Device Mapper storage driver.
* Etcd: Provides dedicated storage for the distributed database used for cluster coordination. This device must be a dedicated device.

See also xref:prereq-verify-disk.adoc[To Verify Disk Requirements] and xref:prereq-verify-device.adoc[To Verify Device Requirements]

==  Network File System (NFS) Server

To use Anypoint Private Cloud, version 2.0+ you must install and configure an NFS server. Before installing or upgrading, you must have an NFS endpoint available. Your NFS server must meet the following requirements:

* Must be running on a filesystem that has at least 250 GB available.
* Must be using NFS version 4.0.
* Can be backed by a network attached storage system (NAS).
* Enable ports 111 and 2049 for both TCP and UDP.
* Configure your network so that all of the PCE nodes can access the NFS server. The direct NFS client is Kubernetes 1.9 and requires conformance with NFS version 4.

To secure your NFS server to work with Anypoint Platform contact your customer success representative.

== Load Balancer

A Load Balancer is required to run Anypoint Platform Private Cloud Edition. See xref:supported-cluster-config.adoc[Supported Network Topologies] and xref:install-create-lb.adoc[To Setup a Load Balancer]

== See Also

* xref:supported-cluster-config.adoc[Supported Network Topologies]
* xref:prereq-verify-disk.adoc[Verify Disk Requirements]
* xref:prereq-verify-device.adoc[Verify Device Requirements]
* xref:verify-nfs.adoc[Verify NFS Server Requirements]
* xref:install-create-lb.adoc[Set up a Load Balancer for Anypoint Platform Private Cloud Edition]
