= Software Requirements for Anypoint Private Cloud
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The following sections list the software required to install and run the Anypoint Platform Private Cloud Edition.

== Supported Linux Distributions
The following Linux distributions are supported:

* Red Hat Enterprise Linux (RHEL), versions 7.4.x, and 7.5.x

* CentOS, versions 7.4.x, and 7.5.x

== SELinux
Anypoint Platform Private Cloud Edition supports the default SELinux profile running in strict mode. If your environment uses a custom profile, it must provide an unconstrained user context when running the installer. Review any custom profiles with your customer support representative.

== Kernel Modules

Ensure that the following kernel modules are enabled:

* `br_netfilter`
* `ebtable_filter`
* `ip_tables`
* `iptable_filter`
* `iptable_nat`

Verify that each module is loaded using the following as an example:

----
root$ lsmod | grep br_netfilter
----

Repeat this command for each of the kernel modules above. If this command does not display any output, then the module is not loaded. In this case, load the module using `modprobe`:

----
root$ modprobe br_netfilter
----

To ensure the module is loaded after a reboot:

----
root$ echo 'br_netfilter' > /etc/modules-load.d/br_netfilter.conf
----

Replace `br_netfilter` with the name of the kernel module you are checking.

== Kernel Settings

The following flags must be turned on:

* `net.bridge.bridge-nf-call-iptables=1`
* `net.ipv4.ip_forward=1`
* `fs.may_detach_mounts=1`
* `fs.inotify.max_user_watches=524288`

Ensure that there are no processes on your system that set this flag to false. To set a parameter you can use `sysctl -w`, for example:

----
root$ sysctl -w net.ipv4.ip_forward=1
----

To make the changes permanent for the next reboot, write it to a file under `/etc/sysctl.d`:

----
echo net.ipv4.ip_forward=1 >> /etc/sysconf.d/10-ipv4-forwarding.conf
----

Replace the setting above with the setting you are configuring. Ensure there are no processes or files conflicting with those settings.
