= Software Prerequisites
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: prereq-verify-software.adoc

To ensure the performance and stability of Anypoint Platform Private Cloud, every node in your Anypoint Platform Private Cloud environment must meet the software prerequisites described in this topic:

* Operating system (OS) prerequisites
* Third party software prerequisites
* MuleSoft software preqrequisites

[IMPORTANT]
Before installing or upgrading, your infrastructure team must review each of the following sections and verify that your environment meets the stated software requirements. If needed, contact your MuleSoft representative for assistance.

== Operating System Prerequisites

=== Verify Linux Distribution
The following Linux distributions are supported:

* Red Hat Enterprise Linux (RHEL), versions 7.4.x, 7.5.x, and 7.6
* CentOS, versions 7.4.x, 7.5.x, and 7.6

=== Check for SELinux Custom Profiles
SELinux is not required, but Anypoint Platform Private Cloud supports the default SELinux profile running 
in strict mode. If your environment uses a custom profile, it must provide an unconstrained user context when 
running the installer. Review any custom profiles with your customer support representative.

=== Enable and Load Kernel Modules

On each node, the following kernel modules must be enabled:

* `br_netfilter`
* `ebtable_filter`
* `ip_tables`
* `iptable_filter`
* `iptable_nat`

For each kernel module, run a command similar to the following example to verify that each module is loaded. Replace `br_netfilter` with the name of the kernel module you are checking.

----
root$ lsmod | grep br_netfilter
----

* If this command does not display any output, then the module is not loaded. In this case, load the module using `modprobe`:
+
----
root$ modprobe br_netfilter
----

To ensure a module is loaded after a reboot:

----
root$ echo 'br_netfilter' > /etc/modules-load.d/br_netfilter.conf
----

=== Verify Kernel Settings

The following flags must be turned on:

* `net.bridge.bridge-nf-call-iptables=1`
* `net.ipv4.ip_forward=1`
* `fs.may_detach_mounts=1`
* `fs.inotify.max_user_watches=524288`

Ensure that there are no processes on your system that set this flag to `false`. To set a parameter, you can use `sysctl -w`, as shown in the following example:

----
root$ sysctl -w net.ipv4.ip_forward=1
----

To make the changes permanent for the next reboot, write it to a file under `/etc/sysctl.d`. Replace the setting in the following example with the setting you are configuring. Ensure there are no processes or files conflicting with those settings.

----
echo net.ipv4.ip_forward=1 >> /etc/sysctl.d/10-ipv4-forwarding.conf
----

== Third Party Software Prerequisites

=== Install Logical Volume Manager 2 (LVM2)

To install and run Anypoint Platform Private Cloud, you must install and use LVM2. LVM2 is a tool that adds a layer of abstraction between your operating system and the disks/partitions it uses. You must have root access to install LVM2.

You can install LVM2 using Yum. Yum is an open-source command-line package-management utility for Linux operating systems using the RPM Package Manager. Using Yum, you can install LVM2 using the following command:

----
sudo yum install lvm2
----

=== Firewall Considerations When Firewalld is Enabled

Firewalld is an iptables controller that defines rules for persistent network traffic.
If you are using firewalld with a Red Hat Enterprise Linux (RHEL) 7.3 operating system, you must enable forwarding on the `docker0` device.
You must also forward any packets being sent from or to the 10.0.0.0/8 subnet.

==== Determine if You Are Using Firewalld

To determine if your system is using firewalld, run the following command on every node:

----
systemctl status firewalld.service
----

If firewalld is installed, this command returns the following:

----
$ sudo systemctl status firewalld.service
* firewalld.service - firewalld - dynamic firewall daemon
Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
Active: inactive (dead)
Docs: man:firewalld(1)
----

If `firewalld is not installed, an error message is displayed.

=== Remove Local DNS Servers

Remove local caching DNS servers listening on port 53, for example, `named`, `dnsmasq`, and `bind`.

=== Install Required Tools

* Tool to Verify NFS Server Ports are Open

** Netcat is recommended, but you can use your tool of choice to verify the correct ports are open on the NFS server. If you don’t have `netcat`, you can install it from  http://netcat.sourceforge.net/download.php or follow the instructions at https://linoxide.com/linux-how-to/install-use-netcat-command-linux/.

== MuleSoft Software Prerequisites

=== Obtain Install Archive and License Key
 
Obtain the `anypoint-2.0.0-installer.tar.gz` archive  and license key from your MuleSoft account representative.

=== Verify IP Forwarding and Bridging

To ensure proper cluster load balancing and routing, you must enable and correctly configure the following items:

* Kernel IP forwarding: to enable internal Kubernetes load balancing you must enable IPv4 forwarding on all servers.
* Bridge-netfilter: enables the Linux kernel to translate packets to and from hosted containers.

** IP addresses for bridge-netfiltering are managed by the overlay network created by Kubernetes. The CIDR block used for that network is in the private IP address range.

=== Enable Forwarding on Docker Device

To enable forwarding on the docker0 device, run the following commands:

----
firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 1 -o docker0 -j ACCEPT -m comment --comment "docker subnet"

firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 1 -s 10.0.0.0/8 -j ACCEPT -m comment --comment "docker subnet"
----

To enable forwarding on the 10.0.0.0/8 subnet, run the following commands:

----
firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT 1 -s 10.0.0.0/8 -j ACCEPT -m comment --comment "docker subnet"

firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT 1 -d 10.0.0.0/8 -j ACCEPT -m comment --comment "docker subnet"
----

== Verify SSL Certificate Requirements

To use the Anypoint Platform Private Cloud, you must provide SSL certificates. You can upload 
a certificate through the Anypoint Platform UI. This certificate must be trusted by every machine that is 
connected to the platform.

[WARNING]
You must register the same SSL certificate on every node containing Mule Runtimes managed by your installation.

=== Uninstall Unsupported Software

The following software causes conflicts with Anypoint Platform Private Cloud. You must uninstall these components before performing Anypoint Platform Private Cloud installation.

==== Docker

Uninstall Docker from all servers running the Anypoint Platform Private Cloud. The Anypoint Platform installation includes a Docker package officially supported by Kubernetes.

== See Also

* xref:prereq-platform.adoc[Environment Prerequisites]
* xref:prereq-hardware.adoc[Hardware Prerequisites]
* xref:prereq-network.adoc[Network Prerequisites]
* xref:verify-nfs.adoc[NFS Server Prerequisites]
