= Workflow: Verify Prerequisites
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This topic describes the workflow for verifying that your environment meets the minimum system requirements to install Anypoint Platform Private Cloud Edition.

[WARNING]
If your system does not meet all of the minimum system requirements, you cannot install Anypoint Platform Private Cloud Edition.

. Contact your customer success representative to obtain a product license for Anypoint Platform Private Cloud Edition.

. xref:prereq-hardware.adoc[Hardware and Device Requirements]
+
Review the minimum hardware and device requirements for Anypoint Platform Private Cloud Edition.

* xref:prereq-verify-disk.adoc[To Verify Disk Requirements]
* xref:prereq-verify-device.adoc[To Verify Device Requirements]
+

. xref:prereq-network.adoc[Network Requirements]
+
About static IPs, network ports and other network requirements.

. xref:prereq-software.adoc[Software Requirements]
+
Supported OS versions and required modules

* xref:prereq-verify-software.adoc[To Uninstall Unsupported Software]
+

. xref:prereq-gravity-check.adoc[Verify System Requirements]
+
Run the `gravity check` tool to verify most requirements automatically.


After installing and verifying these prerequisites, you are ready to perform the installation. See xref:install-workflow.adoc[About Anypoint Platform Private Cloud Edition Installation].