= Software Prerequisites
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: prereq-verify-software.adoc

To ensure the performance and stability of Anypoint Platform Private Cloud Edition (Anypoint Platform PCE), every node in your Anypoint Platform PCE environment must meet the software prerequisites described in this topic:

* Operating system (OS) prerequisites
* MuleSoft software prerequisites

[IMPORTANT]
Before you install Anypoint Platform PCE, your infrastructure team must review each of the following sections and verify that your environment meets the stated software requirements. If needed, contact your MuleSoft representative for assistance.

== Operating System Prerequisites

=== Install required tools

----
yum install -y python3 bash-completion nfs-utils iptables-services
----

==== Tool to Verify NFS Server Ports

Netcat is recommended, but you can use your tool of choice to verify the correct ports are open on the NFS server. If you do not have `netcat`, you can install it from  http://netcat.sourceforge.net/download.php or follow the instructions at https://linoxide.com/linux-how-to/install-use-netcat-command-linux/.

=== Enable and Load Kernel Modules

You must enable the following kernel modules on each node:

* overlay
* br_netfilter
* ebtable_filter
* iptable_nat
* iptable_filter

For each kernel module, run a command similar to the following example to verify that each module is loaded. Replace `br_netfilter` with the name of the kernel module you are checking:

----
root$ lsmod | grep br_netfilter
----

* If this command does not display any output, then the module is not loaded. In this case, load the module using `modprobe`:
+
----
root$ modprobe br_netfilter
----

Ensure a module is loaded after a reboot by using the following command:

----
root$ echo 'br_netfilter' > /etc/modules-load.d/br_netfilter.conf
----

=== Verify Kernel Settings

The following flags must be enabled:

* `net.ipv4.ip_forward=1`
* `net.bridge.bridge-nf-call-iptables=1`
* `fs.inotify.max_user_watches=524288`
* `vm.overcommit_memory=1`

Ensure that no processes on your system overrides any of these flags. To set a parameter, use `sysctl -w`, as shown in the following example:

----
root$ sysctl -w net.ipv4.ip_forward=1
----

To make the changes permanent for the next reboot, write the changes to a file under `/etc/sysctl.d/50-k8s.conf`. Replace the setting in the following example with the setting you are configuring and reload systemd

----
net.ipv4.ip_forward=1
net.bridge.bridge-nf-call-iptables=1
fs.inotify.max_user_watches=524288
vm.overcommit_memory=1
----

Ensure that no processes or files conflict with those settings.

=== Block AWS metadata service

For AWS, block forwarding to AWS metadata service. Not valid for any other cloud providers.

----
iptables -A FORWARD -p tcp -d 169.254.169.254 -j REJECT
----

== MuleSoft Software Prerequisites

=== Obtain Install Archive and License Key
 
Obtain the installer archive (`anypoint-4.x.x-installer.tar.gz`) and license from your MuleSoft account representative.

=== Verify IP Forwarding and Bridging

To ensure proper cluster load balancing and routing, you must enable, correctly configure, and verify the following items:

* Kernel IP forwarding
+
To enable internal Kubernetes load balancing, you must enable IPv4 forwarding on all servers.
* Bridge-netfilter
+
Enable the Linux kernel to translate packets to and from hosted containers.

** IP addresses for bridge-netfiltering are managed by the overlay network created by Kubernetes. Verify that the CIDR block used for that network is in the private IP address range.

== Verify SSL Certificate Requirements

To use the Anypoint Platform PCE, you must provide SSL certificates. You can upload 
a certificate through the Anypoint Platform PCE UI. This certificate must be trusted by every machine that is 
connected to the platform.

[WARNING]
You must register the same SSL certificate on every node containing Mule runtime engines managed by your installation.

== See Also

* xref:prereq-platform.adoc[Environment Prerequisites]
* xref:prereq-hardware.adoc[Hardware Prerequisites]
* xref:prereq-network.adoc[Network Prerequisites]
* xref:verify-nfs.adoc[NFS Server Prerequisites]
