= Installation Infrastructure Prerequisites
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Installing or upgrading Anypoint Platform Private Cloud Edition requires existing infrastructure and specific versions of different software. Without specific versions of operating systems, NFS, and other software, Anypoint Platform Private Cloud Edition cannot run.

Problems occur with the following situations:

* Using your own AWS images
* Using existing provisioning processes that install specific versions of RHEL, Docker, or other software that Anypoint Platform Private CLoud Edition does not support.

[IMPORTANT]
Before beginning an installation or upgrade, make sure your infrastructure team verifies that the following work is complete. Most problems experienced with Anypoint Platform Private Cloud Edition occur because the required environment was not set up. If your system does not meet all of the minimum system requirements, you cannot successfully install or run Anypoint Platform Private Cloud Edition.

Your infrastructure team must verify that the following work is complete. If needed, contact your Customer Success Manager for assistance. 

. xref:prereq-aws-terraform.adoc[Create Anypoint Private Cloud Resources on Amazon Web Services (AWS)]. Cluster set up must be complete and conform to xref:supported-cluster-config.adoc[Supported Network Topologies for Anypoint Private Cloud Edition].
. xref:prereq-hardware.adoc[Verify Hardware Requirements]
. xref:prereq-software.adoc[Verify Software Requirements]
. xref:prereq-network.adoc[Verify Network Requirements]
. xref:verify-nfs.adoc[Verify NFS Requirements]
. A Load Balancer is required to run Anypoint Platform Private Cloud Edition. See xref:supported-cluster-config.adoc[Supported Network Topologies] and xref:install-create-lb.adoc[Setup a Load Balancer].

== See Also

* xref:install-workflow.adoc[Anypoint Private Cloud Installers]
* xref:upgrade.adoc[Upgrade to Anypoint Platform Private Cloud, Version 2.0]
