= Software Requirements for Anypoint Private Cloud
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The following sections list the software required to install and run the Anypoint Platform Private Cloud Edition.

== Supported Linux Distributions
The following Linux distributions are supported:
// How can I check which Linux distribution I have???

* Red Hat Enterprise Linux (RHEL), versions 7.4.x, 7.5.x, and 7.6

* CentOS, versions 7.4.x, 7.5.x, and 7.6

== SELinux
SELinux is not required, but Anypoint Platform Private Cloud Edition supports the default SELinux profile running 
in strict mode. If your environment uses a custom profile, it must provide an unconstrained user context when 
running the installer. Review any custom profiles with your customer support representative.
// SELinux - How do I know if I have a custom profile? How do I contact my customer support rep? What info do I need???

== Kernel Modules
// Enabled = loaded? I got ‘command not found’ - what do I do???

Ensure that the following kernel modules are enabled:

* `br_netfilter`
* `ebtable_filter`
* `ip_tables`
* `iptable_filter`
* `iptable_nat`

Verify that each module is loaded using the following as an example:

----
root$ lsmod | grep br_netfilter
----

Repeat this command for each of the kernel modules above. If this command does not display any output, then the module is not loaded. In this case, load the module using `modprobe`:

----
root$ modprobe br_netfilter
----

To ensure the module is loaded after a reboot:

----
root$ echo 'br_netfilter' > /etc/modules-load.d/br_netfilter.conf
----

Replace `br_netfilter` with the name of the kernel module you are checking.

== Kernel Settings
// How do I turn on the flags? Use info from https://pce-runbook.kbuild.msap.io/content/cluster/modules-and-settings.html#kernel-settings???

The following flags must be turned on:

* `net.bridge.bridge-nf-call-iptables=1`
* `net.ipv4.ip_forward=1`
* `fs.may_detach_mounts=1`
* `fs.inotify.max_user_watches=524288`

Ensure that there are no processes on your system that set this flag to false. To set a parameter you can use `sysctl -w`, for example:
// How do I verify no processes set any flags to ‘false’? What are the values for the flags? Does 1=true? What if some processes are setting flags to ‘false’ - what do I do? Can this cause problems for other stuff if I reset the flags? I got ‘command not found’ on this step.???

----
root$ sysctl -w net.ipv4.ip_forward=1
----

To make the changes permanent for the next reboot, write it to a file under `/etc/sysctl.d`:

----
echo net.ipv4.ip_forward=1 >> /etc/sysctl.d/10-ipv4-forwarding.conf
----

Replace the setting above with the setting you are configuring. Ensure there are no processes or files conflicting with those settings.

== Enable Forwarding When Using firewalld

xref:prereq-firewalld-forwarding.adoc[To Enable Forwarding When Using firewalld]

== Synchronized clocks
// How do I synchronize clocks? Use info from https://pce-runbook.kbuild.msap.io/content/cluster/sync-clocks.html? Does server= node???

Ensure that the clocks on all servers are synchronized. Unsynchronized clocks can cause problems with platform communications.

== See Also

* xref:prereq-verify-software.adoc[To Uninstall Unsupported Software]
