= Other Installation Prerequisites
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

[IMPORTANT]
Before beginning an installation or upgrade, make sure you perform the following tasks. Most problems experienced with Anypoint Platform Private Cloud Edition occur because the required environment was not set up prior to installating or upgrading.

* Verify Level of Expertise Required
* Gather Configuration Information
* Verify Access and Permissions
* Verify Space in Home Directory

== Verify Level of Expertise Required

To install Anypoint Platform Private Cloud Edition, knowledge in the following areas is required:

* Basic knowledge of Linux system commands.
* Basic understanding of remote connection mechanisms, such as SSL and SSH.

== Gather Configuration Information

You will be asked to provide the following information:

* Contact your MuleSoft Customer Success Representative to obtain your Anypoint Platform Private Cloud Edition product license file. For example, `license.pem`.
* Name and location of the installation package. For example, `/home/ec2-user/anypoint-2.0.3-installer.tar.gz`.
* AWS credentials

** Admin ID
** Admin email address
** Admin password
* IP address for each server in the cluster
* Device names

** System state directory
** Application data
** etcd
** Docker

* NFS server information

** NFS server name and path
** PLATFORM_DNS (The DNS must be configured to the NFS server.)

* Anypoint Platform organization and administrator:

** Organization name
** Administrator name
** Administrator email
** Administrator username
** Administrator password

* SMTP server credentials

** Host name
** Port used to communicate to your SMTP server
** User name to authenticate to your SMTP server
** SMTP password

== Verify Access and Permissions

* Before installing or upgrading Anypoint Platform Private Cloud Edition, you must have root access (permission to run the `sudo` command) on all servers in your environment and run the installer or upgrade tool as root to access the necessary, privileged ports.

== Verify Space in Home Directory 

Make sure that you have enough space in your home directory to download and unzip the installer file. The installer is a ~10GB file.

== See Also

* xref:prereq-hardware.adoc[Hardware Prerequisites]
* xref:prereq-software.adoc[Software Prerequisites]
* xref:prereq-network.adoc[Network Prerequisites]
* xref:verify-nfs.adoc[NFS Server Prerequisites]
