= Hardware Prerequisites
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: prereq-verify-disk.adoc, prereq-verify-device.adoc

To ensure the performance and stability of Anypoint Platform Private Cloud Edition (Anypoint Platform PCE), every node in your Anypoint Platform PCE environment must meet the requirements described in this topic. 

[IMPORTANT]
Before you install Anypoint Platform PCE, your infrastructure team must review each of the following sections and verify that your environment meets the stated disk and device requirements. If needed, contact your MuleSoft representative for assistance.

There are 2 components of PCE:

- Anypoint Platform Core
- Anypoint Monitoring (optional)

To ensure platform performance, stability, and high availability, Anypoint Platform Private Cloud Edition (Anypoint Platform PCE) supports two network configurations: 4-node and 7-node.

Small configuration:

- 4 nodes for Control Plane
- 3 additional nodes for Anypoint Monitoring (optional add-on)
- NFS for asset storage
- Load balancer

Large configuration:

- 7 nodes for Control Plane
- 3 additional nodes for Monitoring (optional)
- NFS for asset storage
- Load balancer

To ensure high availability and performance, each node must run on its own server in both configurations. If you are using a virtual machine to host the nodes, you must ensure that each VM node is running on a separate physical server.

== Anypoint Platform Core

Prerequisites for 4-nodes or 7-nodes to run the Anypoint Platform Core.

=== Memory and CPU Requirements

The following are the minimum requirements needed for the Anypoint Platform core. Depending on your environment, you may need more CPU or memory.

[%header%autowidth.spread]
.Memory and CPU Requirements
|===
| Component |Requirement
|RAM |32 GB
|CPU |8 Cores
|===

[IMPORTANT]
If the stated requirements for Memory and CPU are not met, Anypoint Platform PCE installation will fail. 

For production environments, each node in your configuration requires the following EBS volumes:

[%header%autowidth.spread]
.EBS Volumes Requirements
|===
| Volume |Requirement
|/dev/sda1 |200 GB
|/dev/xvdj |256 GB
|===


== Anypoint Monitoring

Anypoint Monitoring is an optional add-on that Anypoint Private Cloud supports. See xref:anypoint-monitoring.adoc[Anypoint Monitoring on Anypoint Platform PCE] for more information.

Prerequisites: The extra 3 nodes for the Monitoring Center Add-On.

=== Memory and CPU Requirements

Monitoring Center Add-On hardware requirements are different from the Platform Core nodes,
they require more CPU, more memory and different disk mounts.

[%header%autowidth.spread]
.Memory and CPU Requirements
|===
| Component |Requirement
|RAM |128 GB
|CPU |32 Cores
|===

[NOTE]
The space requirements listed in the previous table are based on average use. For environments with heavy traffic, validate the amount of space needed with your Customer Success Manager.

Make sure the following directories are mounted on persistent disks following these requirements:

[%header%autowidth.spread]
.Dedicated Device Requirements
|===
| Component |Size|Minimum IOPS|Mount Point|Description
|HDD 4 xref:prereq-hardware#dias-amv-device[Cassandra AMV Device]| 500 GB |1500|/var/lib/data/dias-meld & /var/lib/data/dias-cassandra | Stores Cassandra database data for Monitoring Center Add-On. The amount of space required should be at least 250 GB, but can vary depending on your specific use case. It is important to estimate the minimum size requirements and allocate enough space as a dedicated device ahead of time.
|HDD 5 xref:prereq-hardware#stolon-amv-device[Stolon AMV Device]| 250 GB |1500|/var/lib/data/stolon-amv | Stores Postgres database data for Monitorng Center Add-On. The amount of space required should be at least 250 GB, but can vary depending on your specific use case. It is important to estimate the minimum size requirements and allocate enough space as a dedicated device ahead of time.
|HDD 7 xref:prereq-hardware#influxdb-amv-device[InfluxDB AMV Device]| 4 TB |1500|/var/lib/data/influxdb | Stores InfluxDB data for Monitoring Center Add-On. The amount of space required should be at least 250 GB, but can vary depending on your specific use case. It is important to estimate the minimum size requirements and allocate enough space as a dedicated device ahead of time.
|HDD 7 xref:prereq-hardware#logstash-amv-device[logstash AMV Device]| 500 GB |1500|/var/lib/data/logstash | Stores Logstash data for Monitoring Center Add-On. The amount of space required should be at least 250 GB, but can vary depending on your specific use case. It is important to estimate the minimum size requirements and allocate enough space as a dedicated device ahead of time.
|===

== Load Balancer Requirements
Anypoint Platform PCE must run in a production environment with multiple servers. To distribute traffic among servers and to restrict access to specific ports, you must provide and configure a load balancer.

You can use any load balancer, including NGINX, but NGINX is not required.

=== Load Balancer Configuration
You can configure your load balancer to use any method for distributing client requests, but in most contexts a round robin strategy is ideal. The load balancer should be accessible through an IP address that is available to all machines in your network.

Your load balancer must route the following TCP ports:

[%header%autowidth.spread]
.TCP Port Routing Requirements
|===
|Load Balancer Port |Instance Port | Internal Usage
|`80` | `30080`  | HTTP redirects to HTTPs
|`443` | `30443` | HTTPS port
|`8083` | `30883` | HTTPS port for Mule runtimes to authenticate and renew certificates
|`8889` | `30889` | WebSocket port for Mule runtimes to connect
|`8895` | `30895` | (Only when Monitoring Center is enabled)
|===

In each case, your load balancer must listen on the load balancer port and redirect incoming requests to the instance port. Your Anypoint Platform PCE installation includes an internal NGINX server that listens on each of the configured instance ports, and then performs the action listed in the Internal Usage column.

Your load balancer should poll the address `HTTP:10256/healthz` to run a health check on your platform servers and confirm that they are accessible.

[NOTE]
Do not configure SSL certificates in your load balancer. TLS termination is handled by the platform with the certificates configured using Access Management. See xref:config-workflow.adoc[Configure Anypoint Platform PCE].

=== Implement a Load Balancer Using NGINX

. Enable stream block in your `/etc/nginx/nginx.conf` file by referencing all the configuration properties defined in `/etc/nginx/stream.d/*`.
+
[source,json,linenums]
----
stream {
   include /etc/nginx/stream.d/*.conf;
}
----

. Delete the `default.conf` file from `/etc/nginx/conf.d`
. Create a folder named `/etc/nginx/stream.d` and in it create a file named `onprem.conf`
. Paste the following content in `onprem.conf`
+
[source,json,linenums]
----
server {
   listen 80;
   proxy_pass 0.0.0.0:30080;
}

server {
   listen 443;
   proxy_pass 0.0.0.0:30443;
}

server {	
   listen 8083;	
   proxy_pass 0.0.0.0:30883;	
}

server {
   listen 8889;
   proxy_pass 0.0.0.0:30889;
}

server {
   listen 8895;
   proxy_pass 0.0.0.0:30895;
}
----

. Enable the default ports on SELinux before starting the NGINX. Run the following commands one by one:
+
----
semanage port -a -t http_port_t  -p tcp 8083
semanage port -a -t http_port_t  -p tcp 8889
semanage port -a -t http_port_t  -p tcp 8895
----

. Start NGINX:
+
----
service nginx restart
----

== See Also

* xref:prereq-platform.adoc[Environment Prerequisites]
* xref:prereq-software.adoc[Software Prerequisites]
* xref:prereq-network.adoc[Network Prerequisites]
* xref:verify-nfs.adoc[NFS Server Prerequisites]
* https://www.nginx.com/[Nginx]
* xref:anypoint-monitoring.adoc[Anypoint Monitoring]
