= Private Cloud Edition Network Requirements
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To ensure the performance and stability of Anypoint Platform Private Cloud Edition, every node in your Anypoint Platform Private Cloud Edition environment must meet the network requirements described in this topic. 

//What examples are needed here????

[IMPORTANT]
Before installing or upgrading,  your infrastructure team must review each of the following sections and verify that your environment meets the stated network requirements. If needed, contact your Customer Success Manager for assistance.

== Verify Static IPs

All nodes in the cluster must have static private IPv4 assigned to them, and these must persist after  
restarts. If IP addresses are not persistent between reboots, the cluster can fail.

== Verify VXLAN

The version of Kubernetes supported by Anypoint Platform Private Cloud Edition uses an overlay VXLAN and UDP 
transport to encapsulate traffic. There is direct communication between components of the cluster. The following table 
 lists the ports used for inter-host communication. You must ensure that all of the following ports are 
configured correctly on all nodes.

[%header%autowidth.spread]
|===
|Protocol |Port/Range |Purpose
|TCP/UDP | 53 | Internal cluster DNS
|TCP | 2379, 2380, 4001, 7001 | etcd distributed database
|TCP | 4242 | Installer
|TCP | 6060 | Health check
|TCP | 6443 | Kubernetes API server
|TCP | 7496, 7373 | Serf RPC agent
|TCP | 8080 | Kubernetes API server
|TCP | 10248, 10249, 10250, 10255 | Kubernetes Kubelet
|TCP | 5000 | Docker registry
|TCP | 3008-3012, 3022-3025, 3080, 7496, 7575| Cluster control plane
|TCP | 7000, 7011, 7199, 9042, 9160 | Cassandra
|TCP | 18080, 18443 | Object store cluster
|TCP | 5431-5435, 5973 | Database cluster
|TCP | 30000-32767 | Internal services port range
|TCP | 61008-61010 | Installer port ranges (only used during install)
|TCP | 61022-61024 | Installer port ranges (only used during install)
|UDP | 8472 | Overlay VXLAN network
|TCP | 32009 | Ops Center Admin UI
|===

You can use `netcat` to verify port configuration.
// add validation section to ensure that ports are open. Show node communication with ports open and example. Validate server to server with netcat, test communication betweeen two nodes.??????

== Verify NAT Traffic Requirements

In some situation, the Kubernetes overlay network uses NAT. NAT requires that nodes be able to send and 
receive packages with a source and destination that is different from the node’s internal IP.

Any software that monitors the network traffic must be tuned to allow this type of network interaction.

== Verify SSL Certificate Requirements

To use the Anypoint Platform Private Cloud Edition, you must provide SSL credentials. You can upload 
a certificate through the Anypoint Platform UI. This certificate must be trusted by every machine that is 
connected to the platform.

[WARNING]
You must register the same SSL certificate on every node containing Mule Runtimes managed by your installation.

== Verify SMTP Server Requirements

Your network must include an SMTP server to manage e-mail alerts that are triggered by the platform.

== Verify External Identity Provider and Client Management 

To configure an Exernal Identity Provider for users single sign on (LDAP, OpenID, SAML) or for external 
client management as OpenID Connect, the cluster must be able to access the External Identity Provider endpoint. 

== Verify IP Forwarding and Bridging

To ensure proper cluster load balancing and routing, you must enable and correctly configure the following:

* Kernel IP forwarding: to enable internal Kubernetes load balancing you must enable IPv4 forwarding on all servers.
* Bridge-netfilter: enables the Linux kernel to translate packets to and from hosted containers.

** IP addresses for bridge-netfiltering are managed by the overlay network created by Kubernetes. The CIDR block used for that network is in the private IP address range.

== See Also

* xref:prereq-software.adoc[About Software Requirements]
* xref:supported-cluster-config.adoc[Supported Network Topologies]
