= Installation Prerequisites
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Infrastructure Requirements
Installing or upgrading Anypoint Platform Private Cloud Edition requires existing infrastructure and specific versions of different software. Without specific versions of operating systems, NFS, and other software, Anypoint Platform Private Cloud Edition cannot run.

Problems occur with the following situations:

* Using your own AWS images
* Using existing provisioning processes that install specific versions of RHEL, Docker, or other software that Anypoint Platform Private CLoud Edition does not support.

Before beginning an installation or upgrade, make sure that you contact your infrastructure team to verify that the minimum  requirements that are described are met. Most problems experienced with Anypoint Platform Private Cloud Edition occur because the required environment was not properly set up prior to Anypoint Platform Private Cloud Edition installation or upgrade.

[IMPORTANT]
Your infrastructure team must verify that the following work is complete. If needed, contact your Customer Success Manager for assistance. If your system does not meet all of the minimum system requirements, you cannot successfully install Anypoint Platform Private Cloud Edition.

 * xref:prereq-aws-terraform.adoc[Create Anypoint Private Cloud Resources on Amazon Web Services (AWS)]
 
 ** Cluster set up must be complete and conform to xref:verify cluster setup is complete and conforms to xref:supported-cluster-config.adoc[Supported Network Topologies for Anypoint Private Cloud Edition].
 * xref:prereq-hardware.adoc[Verify Hardware Requirements]
 * xref:prereq-software.adoc[Verify Software Requirements]
 * xref:prereq-network.adoc[Verify Network Requirements]
 * xref:verify-nfs.adoc[Verify NFS Requirements]
 
 
 ???
 * Each node must be running on its own server. If you are using a virtual machine to host these nodes, you must ensure that each VM node is running on a separate physical server. How can I verify this?
* Each of your nodes is configured with database and object store as described in <link to Supported Network Topologies> topic.
* All nodes have access to NFS server.
 
 ???
 
 

== Access and Permissions

* Before installing Anypoint Platform Private Cloud Edition, you must have root access (permission to run the `sudo` command) on all servers in your environment. This applies to both the CLI and GUI installers and for upgrades.

== Information Needed for Installation

* Contact your customer success representative to obtain your Anypoint Platform Private Cloud Edition product license file. For example, `license.pem`.
* Name and location of the installation package. For example, `/home/ec2-user/anypoint-2.0.3-installer.tar.gz`.
* AWS credentials

** Admin ID
** Admin email address
** Admin password
* Cluster name
* Secret token for the cluster 
* IP address for each server in the cluster
* Device names

** Docker
** Location where Anypoint Platform data is stored.

* NFS server information

** NFS server name and path
** PLATFORM_DNS (The DNS must be configured to the NFS server.)

* SMTP server??? What info is needed???

* Anypoint Platform organization and administrator:

** Organization name
** Administrator name
** Administrator email
** Administrator username
** Administrator password

== Tools

* Netcat commands must be run to verify ports are open on NFS server. If you don’t have the netcat tool, install it from here: http://netcat.sourceforge.net/download.php -  which download is appropriate??? Additional reference info: https://linoxide.com/linux-how-to/install-use-netcat-command-linux/

** Ensure the `kubectl` command is available on the node where you are performing the installation or migration. To verify that `kubectl` is installed, run the following:
+
----
$ sudo gravity enter
$ kubectl
----
// What do I do if it's not available???

** Enable TCP ports `53`, `3011`, `3012` intra-node to allow communication with the database cluster.


* Must configure a load balancer with round robin distribution among 3 nodes. What about 6 nodes?

// Knowledge required to install PCE: OS, File System, SSL certs, How to open ports.
// Linux admin level of knowledge? Familiarity with Linux commands???


== Load Balancer

A Load Balancer is required to run Anypoint Platform Private Cloud Edition. See xref:supported-cluster-config.adoc[Supported Network Topologies] and xref:install-create-lb.adoc[To Setup a Load Balancer]


== To Manually Reset Devices and Partitions
// THIS IS A DUP FROM UNINSTALL INSTRUCITONS. POSSIBLY MOVE TO MANUAL RESET SECTION. How do you reset a partition? What does ‘reset’ mean? Says remove. Where is this run from???

Logical Volume Manager allows one to group multiple physical volumes into a single storage volume (Volume Group) and then divide these into Logical
Volumes. Physical Volumes are either a whole device or a partition.

In some cases when a device is in use by another logical volume or you want to manually reset a device previously configured for Device Mapper the following commands may be useful.

The Logical Volume Manager toolset consists of the following commands:
  * dmsetup - is a low-level logical volume management
  * pv/vg/lv-prefixed commands like pvdisplay and pvcreate/pvremove - for working with specific LVM object types (i.e. lv - for logical volumes and vg - for volume groups)

To reset a device use the following commands:

* remove logical volume with `lvremove -f docker/thinpool` (use `lvdisplay` to find the volume to remove)
* remove volume group with `vgremove docker` (use `vgdisplay` to locate the volume group to remove)
* remove physical volume and reset device with `pvremove /dev/<device name>` (use `pvdisplay` to find the physical volume to remove and the device name it is on)

== Checking Block Devices
// THIS IS A SUMMARY OF VALIDATING YOUR CONFIG IS OK. PUT IN VALIDATE SECTION. This is what it looks like after checking, What if my output doesn't look like the example???

Before installing block devices must be similar in all nodes. The output of running *lsblk* should be as below: 

----
[root@ip-0-0-0-0 ~]# lsblk
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
xvda 202:0 0 90G 0 disk
├─xvda1 202:1 0 1M 0 part
└─xvda2 202:2 0 90G 0 part /
xvdb 202:16 0 100G 0 disk -- Docker volume (not formatted)
xvdc 202:32 0 20G 0 disk /var/lib/gravity/planet/etcd
xvdd 202:48 0 250G 0 disk /var/lib/data
xvde 202:64 0 100G 0 disk /var/lib/gravity
xvdf 202:64 0 20G 0 disk /tmp
----

Also make sure that you have enough space in your home directory to download and unzip the installer file. The installer is a ~10GB file.
// How do I check the amount of space in the home directory to make sure it’s enough for 10 GB installer file??? Get command from Fed???????? THIS INFO SHOULD BE IN MAIN CHECKLIST.



== Install Anypoint Platform Private Cloud Edition

After provisioning resources in your AWS environment and uploading the installer to one of the nodes, install Anypoint Platform Private Cloud Edition using one of the installers:
// How do I upload the installer to one of the nodes? (or did we do this already)? Does it matter which node???


== Disabling Port 61009 After Installation

After installation is finished you can close port 61009 in the cluster security group using the AWS Web console.




If you are upgrading, perform a backup of your system as described in xref:backup-and-disaster-recovery.adoc[About Backup and Recovery, role=external, window=_blank]. 

If you are upgrading from an older version that requires multiple intermediate upgrades you must back up each intermediate version before proceeding to the next version.
Make sure your environment meets all requirements <link????)

See also
Install
Upgrade - links?????
