= Preinstallation Checklist
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Before installing or upgrading Anypoint Platform Private Cloud Edition, you must verify that your environment meets the minimum system requirements.
// Does node = instance? Terminology is confusing. Needs to be consistent.???

If your system does not meet all of the minimum system requirements, you cannot successfully install Anypoint Platform Private Cloud Edition.

If you are upgrading, perform a backup of your system as described in xref:backup-and-disaster-recovery.adoc[About Backup and Recovery, role=external, window=_blank]. 

If you are upgrading from an older version that requires multiple intermediate upgrades you must back up each intermediate version before proceeding to the next version.

Gather all the information listed in the following steps and install the tools needed for the installation.

. Contact your customer success representative to obtain the product license file for Anypoint Platform Private Cloud Edition.
// How do I contact my rep??? Does PCE use the same license file?

. Verify AWS account set up with your infrastructure team. Credentials needed include:
// Is there a possibility that this hasn't been done yet??? Name = ID???
** Admin ID
** Admin email address
** Admin password
** IP addresses for all Anypoint Private CLoud Edition nodes.

. Follow the procedures described in https://docs.mulesoft.com/private-cloud/2.0/prereq-aws-terraform[Create Anypoint Private Cloud Resources on Amazon Web Services (AWS)]. If someone else set up your AWS cluster, verify cluster setup is complete and conforms to <link to architecture topic????>. This includes device set up as described in <Device requirements topic link??????>.??????
// How can this be checked???

* You must have 3 or 6 instances set up as described in <link>. Which instance type and how do I verify the instance type? T2.medium?
* Each node must be running on its own server. If you are using a virtual machine to host these nodes, you must ensure that each VM node is running on a separate physical server. How can I verify this?
* Each of your nodes is configured with database and object store as described in <link to Supported Network Topologies> topic.
* Each node must have HDD1, 2, 3, 4, 5, 1 tmp.
* All nodes have access to NFS server.
* Name of the cluster
* Secret token for the cluster 
* IP address for each server in the cluster
* Docker device name on each server
* Must configure a load balancer with round robin distribution among 3 nodes. What about 6 nodes?

. You must have an NFS server installed and configured before installing or upgrading Anypoint Private Cloud Edition. Ensure that your current environment meets the minimum requirements described in xref:verify-nfs.adoc[Verify NFS Server Requirements, role=external, window=_blank]. Obtain the following NFS server information needed:

** Server/host name and path
** PLATFORM_DNS (The DNS must be configured to the NFS server.)

. SMTP server??? What info is needed???

. Name and location of the installation package. For example, `/home/ec2-user/anypoint-2.0.3-installer.tar.gz`.

. Obtain the following information about your organization and Anypoint Platform administrator:
// Is there any chance that Anypoint Platform isn't set up yet???

** Organization name
** Administrator name
** Administrator email
** Administrator username
** Administrator password
** Location where Anypoint Platform data is stored.
** The Anypoint Private Cloud Edition license file. For example, `license.pem`.
// Should org name be the same as cluster deployment? How can I find out where Anypoint platform data is stored if it’s not the default? How much is enough disk space???

. Verify the following software-related items:

** Netcat commands must be run to verify ports are open on NFS server. If you don’t have the netcat tool, install it from here: http://netcat.sourceforge.net/download.php -  which download is appropriate??? Additional reference info: https://linoxide.com/linux-how-to/install-use-netcat-command-linux/
Ensure you have permission to run the `sudo` command on the node from which you plan to launch the installation or migration.
** Ensure the `kubectl` command is available on the node where you are performing the installation or migration. To verify that `kubectl` is installed, run the following:
+
----
$ sudo gravity enter
$ kubectl
----
// What do I do if it's not available???

** Enable TCP ports `53`, `3011`, `3012` intra-node to allow communication with the database cluster.

. xref:prereq-hardware.adoc[Hardware and Device Requirements]

** xref:prereq-verify-disk.adoc[Verify Disk Requirements]
** xref:prereq-verify-device.adoc[Verify Device Requirements]

. xref:prereq-network.adoc[Network Requirements]
. xref:prereq-software.adoc[Software Requirements]
. xref:prereq-verify-software.adoc[To Uninstall Unsupported Software]
. xref:prereq-gravity-check.adoc[Verify System Requirements]
// This is a confusing title - everything here is basically a 'system' requirement.??? Need a list of what `gravity check` checks and what it doesn't.???
