= Network Prerequisites
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: prereq-firewalld-forwarding.adoc, install-create-lb.adoc

To ensure the performance and stability of Anypoint Platform Private Cloud Edition (Anypoint Platform PCE), every node in your Anypoint Platform PCE environment must meet the network requirements described in this topic.

[IMPORTANT]
Before you install Anypoint Platform PCE, your infrastructure team must review each of the following sections and verify that your environment meets the stated network requirements. If needed, contact your MuleSoft representative for assistance.

== Verify Static IPs

All nodes in the cluster must have static private IPv4 assigned to them, and these must persist after restarts. If IP addresses are not persistent between reboots, the cluster can fail.

== Port Requirements

The following table lists the ports used for inter-host communication. The table uses the following source and destination descriptions:

* Anypoint Platform PCE nodes: Nodes that are members of the cluster.
* Load Balancer: Any source that is outside the cluster.
* localhost: The port that is used only within the host where the request started.

You must ensure that all the following ports are configured correctly on all nodes.

[%header%autowidth.spread]
.Port Configuration Requirements
|===
|Protocol |Port/Range |Purpose |Source |Destination
|TCP/UDP | 53 | Internal cluster DNS | localhost | localhost
|TCP | 2379, 2380 | etcd distributed database | Anypoint Platform PCE nodes | Anypoint Platform PCE nodes
|TCP | 6443 | Kubernetes API server | Anypoint Platform PCE nodes | Anypoint Platform PCE nodes
|TCP | 9100 | Prometheus node-exporter | Anypoint Platform PCE nodes | Anypoint Platform PCE nodes
|TCP | 10248, 10250 | Kubernetes Kubelet | Anypoint Platform PCE nodes | Anypoint Platform PCE nodes
|TCP | 10249 | Kubernetes kube-proxy | localhost | localhost
|TCP | 10251-10252 | Kubernetes controller-manager and scheduler | Anypoint Platform PCE nodes | Anypoint Platform PCE nodes
|TCP | 10257-10259 | Kubernetes controller-manager and scheduler (secure) | Anypoint Platform PCE nodes | Anypoint Platform PCE nodes
|TCP | 5000 | Docker registry | Anypoint Platform PCE nodes | Anypoint Platform PCE nodes
|TCP | 30000-32767 | Internal services port range | Anypoint Platform PCE nodes | Anypoint Platform PCE nodes
|UDP | 8472 | Overlay VXLAN network | Anypoint Platform PCE nodes | Anypoint Platform PCE nodes
|TCP | 30080 | HTTP public access | Load Balancer | Anypoint Platform PCE nodes
|TCP | 30443 | HTTPS public access | Load Balancer | Anypoint Platform PCE nodes
|TCP | 30889 | Mule Runtime Websocket | Load Balancer | Anypoint Platform PCE nodes
|TCP | 30883 | Mule Runtime Authentication Service (for certificate renewals) | Load Balancer | Anypoint Platform PCE nodes
|===

You can use netcat or a similar utility to verify port configuration.

== Verify NAT Traffic Requirements

In some situations, the Kubernetes overlay network uses NAT. NAT requires that nodes be able to send and
receive packages with a source and destination different from the node’s internal IP.

Any software that monitors the network traffic must be tuned to allow this type of network interaction.

== Disable OS NetworkManager Services
In some operating systems, like RHEL/CentOS 8.4, NetworkManager includes two extra services: `nm-cloud-setup.service` and `nm-cloud-setup.timer`. These services add routing tables that interfere with the configuration of the Kubernetes Container Network Interface (CNI) plugin. If those services exist, disable them and restart the node before proceeding with the installation.

== Verify SMTP Server Requirements
Your network must include an SMTP server to manage email alerts that are triggered by the platform. Anypoint Platform PCE must be connected to this SMTP server.

For additional information, refer to the instructions in xref:access-management-SMTP.adoc[Configure SMTP in Anypoint Platform PCE].

== Verify External Identity Provider Configuration and Client Management
Your network must include an external identity provider that is compatible with LDAP, OpenIDConnect, or SAML. To configure an External Identity Provider for user SSO (LDAP, OpenIDConnect, and SAML) or for external client management as OpenID Connect, the cluster must be able to access the external identity provider endpoint.

For additional information, refer to the instructions in xref:install-config-ldap-pce.adoc[Configure an External Identity Provider in Anypoint Platform PCE].

== Synchronize Clocks

Ensure that the clocks on all servers are synchronized. Unsynchronized clocks can cause problems with platform communications.

== See Also

* xref:prereq-platform.adoc[Environment Prerequisites]
* xref:prereq-hardware.adoc[Hardware Prerequisites]
* xref:prereq-software.adoc[Software Prerequisites]
* xref:verify-nfs.adoc[NFS Server Prerequisites]
