= Hardware Requirements for Anypoint Private Cloud
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To ensure the performance and stability of Anypoint Platform Private Cloud Edition, every node in your Anypoint Platform Private Cloud Edition environment must meet the system requirements described in this topic. Before installing or upgrading, review each of the following sections and ensure that your environment meets these requirements.

You cannot install Anypoint Platform Private Cloud Edition unless all nodes meet all of the minimum system requirements.

== Memory and CPU Requirements
// How can I verify that I have enough RAM and CPU cores???

[%header%autowidth.spread]
|===
| Component |Requirement
|RAM |32 GB
|CPU |8 Cores
|===

== Disk Size and Performance Requirements
//Include info from https://pce-runbook.kbuild.msap.io/content/cluster/disk-space.html???

Anypoint Platform Private Cloud Edition has strict minimum size and performance requirements for storage devices used by the platform. All disk drives must meet the following criteria:

* Must have at least 300 MB/sec of throughput.
* Must have high performance capability, even if they are virtual block devices or network attached storage.
//How do I verify these and how do I know whether I have virtual block devices or network attached storage or something else???

For production environments, each node in your configuration must have the following devices and the devices must meet the stated minimum requirements.
//How are these set up (who sets them up) and how do I verify this???
// How do I verify disk size???

[%header%autowidth.spread]
|===
| Component |Size|Minimum IOPS|Mount Point
|HDD 1 ()perating system) |50 GB |500|
|HDD 2 (System data) | 100 GB |1500|/var/lib/gravity
|HDD 3 (Application data)| 250 GB |1500|/var/lib/data
|HDD 4 (Docker) | 100 GB |3000|Not mounted
|HDD 5 (Etcd) | 20 GB |3000|/var/lib/gravity/planet/etcd
|/tmp (Installer) | 20 GB |N/A|
|===
//Feedback received indicated that the gravity check failed when Installer had 20 GB. Is 25 enough? 50?

The devices must be formatted either as *xfs* or *ext4*, and each node must have dedicated devices:
//How do I check *xfs* or *ext4*?

* System data: Stores system configuration and metadata, including databases and packages. As package sizes can be large, it is important to estimate the minimum size requirements and allocate enough space as a dedicated device before installation.
//Guidance for estimating the minimum size requirements???
* Application data: Stores application configuration and data. The amount of space required should be at least 250 GB, but might vary depending on your specific use case. It is important to estimate the minimum size requirements and allocate enough space as a dedicated device ahead of time.
//Guidance for estimating the minimum size requirements???
* Docker: Used by Docker’s Device Mapper storage driver.
* Etcd: Provides dedicated storage for the distributed database used for cluster coordination.

//Verify Disk Device requirements (move https://docs.mulesoft.com/private-cloud/2.0/prereq-verify-disk to here???
Verify Anypoint Private Cloud Disk Device Requirements - ADD CONTENT HERE
//Is this done on each node?




==  Network File System (NFS) Server

// Can this be consolidated with the other NFS info???

To use Anypoint Private Cloud, version 2.0+ you must install and configure an NFS server. Before installing or upgrading, you must have an NFS endpoint available. Your NFS server must meet the following requirements:

* Must be running on a filesystem that has at least 250 GB available.
* Must be using NFS version 4.0.
* Can be backed by a network attached storage system (NAS).
* Enable ports 111 and 2049 for both TCP and UDP.
* Configure your network so that all of the PCE nodes can access the NFS server. The direct NFS client is Kubernetes 1.9 and requires conformance with NFS version 4.

To secure your NFS server to work with Anypoint Platform contact your customer success representative.

== Load Balancer

A Load Balancer is required to run Anypoint Platform Private Cloud Edition. See xref:supported-cluster-config.adoc[Supported Network Topologies] and xref:install-create-lb.adoc[To Setup a Load Balancer]

== See Also

* xref:supported-cluster-config.adoc[Supported Network Topologies]
* xref:prereq-verify-disk.adoc[Verify Disk Requirements]
* xref:prereq-verify-device.adoc[Verify Device Requirements]
* xref:verify-nfs.adoc[Verify NFS Server Requirements]
* xref:install-create-lb.adoc[Set up a Load Balancer for Anypoint Platform Private Cloud Edition]
