= Troubleshoot Mule Runtime Engine Registration
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

If you encounter an error when performing the steps in xref:runtime-manager::servers-create.adoc[Create a Server in Runtime Manager]:

Before registering Mule runtime engine, you must configure Mule to trust the TLS certificates you configured:

.. Get the public certificate for Mule runtime engine.
.. Add the certificate to the truststore of the JVM you are using for the Mule runtime engine.

In the following example, $ANYPOINT_DNS should be set to your DNS for Anypoint Platform Private Cloud Edition.
Replace the keystore location and password for your JVM's truststore.
For more information on what is the cacerts truststore refer to your JVM version documentation. For instance, https://docs.oracle.com/en/java/javase/17/security/java-security-overview1.html#GUID-EB29B931-D1DE-420B-849C-D731A8DF9CDC[Oracle's documentation].

For example:

----
$ keytool -printcert -sslserver $ANYPOINT_DNS:443 -rfc > /tmp/anypoint.crt
$ keytool -importcert -alias anypoint.my-company -keystore /etc/ssl/certs/java/cacerts -storepass changeit -file /tmp/anypoint.crt
----



