= Troubleshooting Mule Runtime Engine Registration
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

If you encounter a Mule runtime engine (Mule) registration error when xref:runtime-manager::servers-create.adoc[creating a server in Runtime Manager], configure Mule to trust the TLS certificates you are using. 

To do so:

. Get the public certificate for Anypoint Platform Private Cloud Edition (Anypoint Platform PCE).
. Add the certificate to the truststore of the JVM you are using for Mule.

Using the following example, set `$ANYPOINT_DNS` to your DNS for Anypoint Platform PCE. Replace the keystore location and password for your JVM truststore.

----
$ keytool -printcert -sslserver $ANYPOINT_DNS:443 -rfc > /tmp/PCE_Certificate.cer
$ keytool -importcert -alias anypoint.my-company -keystore <path to keystore> -storepass changeit -file /tmp/PCE_Certificate.cer
----

For more information about the CA certificate truststore, see your JVM vendor's documentation: https://docs.oracle.com/[Oracle documentation^].

== See Also

* xref:operating-about.adoc[]