= Troubleshoot Mule Runtime Engine Registration
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

If you encounter a Mule runtime engine registration error when xref:runtime-manager::servers-create.adoc[creating a server in Runtime Manager], you might need to configure Mule to trust the TLS certificates you are using. 

To do so:

. Get the public certificate for Anypoint Platform Private Cloud Edition.
. Add the certificate to the truststore of the JVM you are using for the Mule runtime engine.

Using the following example, set `$ANYPOINT_DNS` to your DNS for Anypoint Platform Private Cloud Edition. Replace the keystore location and password for your JVM truststore.

----
$ keytool -printcert -sslserver $ANYPOINT_DNS:443 -rfc > /tmp/PCE_Certificate.cer
$ keytool -importcert -alias anypoint.my-company -keystore <path to keystore> -storepass changeit -file /tmp/PCE_Certificate.cer
----

For more information about the CA certificate truststore, refer to your JVM vendor's documentation: for example,  https://docs.oracle.com/en/java/javase/17/security/java-security-overview1.html#GUID-EB29B931-D1DE-420B-849C-D731A8DF9CDC[Oracle documentation^].



