= Stop, Restart, or Update an Anypoint Private Cloud Edition Node
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Before You Begin

* Set up and test the backup procedure on all clusters after you complete installation.
* Perform a backup before attempting node maintenance to preserve data in the event of a failure.

== Cluster and Application Updates

The following steps must be performed on one Anypoint Platform Private Cloud Edition node at a time to minimize or eliminate component breakage during the update process. The entire process must be completed on each node before the next node is addressed. Verify the health status of all cluster components and applications after each node update before proceeding with the next node.

This approach assumes that multiple masters are running.

=== Verify Cluster Status

Verify that the cluster is healthy before starting the process. Otherwise, many of the assumptions made in this process are not valid.

. Verify the output from the following commands:
+
```
gravity status
etcdctl cluster-health
gravity get pod -o wide--all-namespaces | grep -vi Running
gravity get deployment --all-namespaces
gravity get daemonset --all-namespaces
```
. Review log entries or status message that indicate the possibility of an unhealthy node.

. Verify that replication works and is healthy in any replicated software (like Stolon and Cassandra).

=== Install Updates

After verifying that the cluster is healthy, drain a node.

. Retrieve the *name* of the target node:
+
```
kubectl get nodes
```
. Drain the node:
+
```
kubectl drain --delete-local-data --ignore-daemonsets <node_name>
```
. After the node is drained, identify the gravity unit name:
+
```
sudo systemctl list-units --plain | awk '/planet-master/{print $1}'
```
. Stop the unit:
+
```
systemctl stop $unit_name
systemctl status $unit_name
```
. After the `status` subcommand indicates the unit is stopped, install the needed updates and reboot the server.

=== Perform Post-update Check

. Verify that all systems correctly restarted:
+
```
systemctl status --failed
```
. Check the gravity `systemd` units:
+
```
systemctl list-units '*gravitational*'
```
. Check for errors in the logs by running `journalctl`.

. If everything started correctly, run `gravity enter` and verify the results.

. Check the cluster status again:
+
```
gravity status
etcdctl cluster-health
gravity get pod -o wide--all-namespaces | grep -vi Running
gravity get deployment --all-namespaces
gravity get daemonset --all-namespaces
```

=== Rejoin the Node

. Check the gravity Planet master and teleport status:
+
```
systemctl list-units '*gravity__gravitational*'
```

. If the status of the gravity service is not `loaded`, `active`, or `running`, then you must enable it:
+
```
systemctl enable --now <name_of_the_gravity_unit>
```

. Uncordon the node:
+
```
kubectl uncordon <node_name>
```

. Verify cluster status:
+
```
gravity status
```
+
This command should display a `healthy` status for all nodes of the cluster. After you verify that the node has rejoined the cluster and is in healthy status, repeat the process for the next node in the cluster.
****
