= Stop, Restart, or Update an Anypoint Private Cloud Edition Node
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Before You Begin

* Set up and test the backup procedure on all clusters after you complete installation.
* Perform a backup before attempting node maintenance to preserve data in the event of a failure.

== Cluster and Application Updates

[IMPORTANT]
The following steps must be performed on one Anypoint Platform Private Cloud Edition node at a time to minimize or eliminate component breakage during the update process. The entire process must be completed on each node before the next node is addressed. Verify the health status of all cluster components and applications after each node update before proceeding with the next node.

=== Verify Cluster Status

Verify that the cluster is healthy before starting the process. Otherwise, many of the assumptions made in this process are not valid.

. Verify the output from the following commands:
+
```
gravity status
etcdctl cluster-health
```

If the output from any of the two commands above mentions `degraded` state or `errors` please be sure to fix the mentioned issue, before proceeding.

Please also verify that all Pods are running by running the commands below:
```
gravity get pod -o wide--all-namespaces | grep -vi Running
```
And if the command above lists any Pod, which will not be in "Running" state, then it means that it's probably having some issues and needs to be fixed.

. Verify that replication works and is healthy in any replicated software (like Stolon and Cassandra).
-- TODO link to Stolon and Cassandra troubleshooting here

=== Install Updates

After verifying that the cluster is healthy, proceed with the process by draining the first node.

. Retrieve the *name* of the target node:
+
```
kubectl get nodes
```
. Drain the node:
+
```
kubectl drain --delete-local-data --ignore-daemonsets <node_name>
```
. After the node is drained, identify the gravity unit name:
+
```
sudo systemctl list-units --plain | awk '/planet-master/{print $1}'
```
The command above will output a systemd unit name, copy it as you will need to use it in the following commands instead of `$unit_name`.
. Stop the unit:
+
```
systemctl stop $unit_name
systemctl status $unit_name
```
. After the `status` subcommand indicates the unit is stopped, install the needed updates and reboot the server.

=== Perform Post-update Check

. Verify that all systems correctly restarted:
+
```
systemctl status --failed
```
This command should return zero units which means that your system boot phase went correctly and no unit failed to start. if there's any unit which had issues, please inspect the problem and fix it before proceeding.
. Check the gravity `systemd` units:
+
```
systemctl list-units '*gravity__gravitational*'
```
. Check for errors in the logs by running `journalctl`.

. If everything started correctly, run `gravity enter` and verify the results.

. Check the cluster status again:
+
```
gravity status
etcdctl cluster-health
gravity get pod -o wide--all-namespaces | grep -vi Running
```

=== Rejoin the Node

. Check the gravity Planet master and teleport status:
+
```
systemctl list-units '*gravity__gravitational*'
```

. If the status of the gravity service is not `loaded`, `active`, or `running`, then you must enable it:
+
```
systemctl enable --now <name_of_the_gravity_unit>
```

. Uncordon the node:
+
```
kubectl uncordon <node_name>
```
This operation will set the target node to schedule Pods again. It may take a few minutes to complete.

. Verify cluster status:
+
```
gravity status
```
+
This command should display a `healthy` status for all nodes of the cluster. After you verify that the node has rejoined the cluster and is in healthy status, repeat the process for the next node in the cluster.
****
