= Supported Platform Components and Configuration

[WARNING]
====
The recommendations and limits provided in this topic are based on the following resources:

* A 4-node environment consisting of 4 nodes of 8 cores and 32GB RAM, or
* A 7-node environment consisting of 7 nodes of 8 cores and 32GB RAM.
====


== Mule Runtime Server and Mule Applications

The following table shows the recommended and maximum number of Mule runtime servers and Mule applications that Anypoint Platform PCE supports:

[%header%autowidth.spread]
.Mule Runtime Server
|===
| | 4-node Configuration | 7-node Configuration
| Maximum number of servers per environment | 500 | 500
| Maximum number of servers across all environments | 1500 | 3000
| Maximum number of servers per server group | 20 | 20
| Maximum servers per cluster | 8 | 8
| Mule applications under management per environment (recommended) | Under 200 | Around 200
| Mule applications under management per environment (maximum) | 500 | 500
| Mule runtime engines under management (maximum) | 500 single Mule runtime engines, or 250 Mule runtime clusters, consisting of 2 Mule runtime engines per cluster | 1000 single Mule runtime engines, or 500 Mule runtime clusters, consisting of 2 Mule runtime engines per cluster
| Mule applications per Mule runtime engine (recommended) | Fewer than 25 | Fewer than 25
| Mule applications per Mule runtime engine (maximum) | 100 | 50
|===


==  Anypoint Monitoring and Visualizer

Anypoint Platform PCE includes Anypoint Monitoring and Anypoint Visualizer. However, some features of these platform components are not supported as described in the following sections.

===  Anypoint Monitoring

Anypoint Platform PCE does not the support the following Anypoint Monitoring features:

** Support for Mule 3.8.x
** Log Management. As an alternative, use your server's logging capabilties or a third-party vendor like Splunk.
** Increased storage capacity. This is not required since the Archive API is not supported.
** Archive API. This API is not applicable since log management is not supported.
** API Functional Monitoring. As an alternative, use a third-party vendor like Pingdom.
** The *Tools* tab of Anypoint Monitoring is not included on Anypoint Platform PCE

=== Visualizer

Anypoint Platform PCE does not the support the following Anypoint Visualizer features:

* List of applications. If an application does not use Anypoint Monitoring, it cannot be tracked by Anypoint Visualizer on Anypoint Platform PCE.
* Policy visualization.
