= Troubleshoot NFS Errors
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

[IMPORTANT]
Setting up and configuring an NFS server should be performed by your infrastructure team. If you experience problems with any of the following instructions, contact your infrastructure team for assistance.

You must have a connection from each node to NFS.

== “Server Not Responding”

Use a tool such as ping, traceroute, or tracepath to verify that the client and server machines can communicate with each other. If communication fails between the client and server machines, examine the network interface card (NIC) settings using either `ifconfig` or `ethtool` to verify the IP settings.

== “Access Denied” or "Permission Denied"

Check the export permissions for the NFS file system. You can do this from the client or from the server.

From the client:

`showmount -e server_name`

From the server:

`exportfs -a`

== "rpc mount export: RPC: Timed out"

The error message `Unable to access file system at [NFS SERVER]: rpc mount export: RPC: Timed out` is caused by a DNS name resolution issue. NFS (RPC) needs reverse name resolution. If the NFS server or client cannot resolve their name, this error occurs. Check the DNS configuration and the `/etc/hosts` configuration.

== Mounting the NFS Server Fails

If the mount fails, you are probably missing some NFS-required libraries. If this happens, install them by running: +
`yum install nfs-utils nfs-utils-lib`

=== "mount failed: Not Permitted"

The error message `mount failed: exit status 32. Mounting command ... not permitted` may occurr when trying to mount with the `noresvport` option since the ports may be limited. If this happens, remove the `noresvport` option and add the `insecure` flag to the mounting command.

== See Also

* xref:verify-nfs.adoc[Verify NFS Server Communication]
