= Upgrade to Anypoint Platform Private Cloud, Version 2.0
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This topic provides information about upgrading Anypoint Platform Private Cloud Edition to the most recent version. This version supports the following migration paths:

[%header%autowidth.spread]
|===
| Base Version | Intermediate Versions | Target Version | Comments
| 1.7.x | N/A | 2.0 | Direct upgrade is supported
| 1.6.x | 1.7.1 | 2.0 | Must upgrade to version 1.7.1
| 1.5.x | 1.6.1, 1.7.1 | 2.0 | Must upgrade to 1.6.1, then 1.7.1 before upgrading to 2.0.
|===

The following table summarizes the features included in Anypoint Platform Private Cloud Edition version 1.7 and version Anypoint Platform Private Cloud Edition 2.0.

[%header%autowidth.spread]
|===
| Component | Feature | 1.7 Feature Version | 2.0 Feature Version
| API Platform | Platform API | 1.16.5-rc.2 | 2.2.13-rc.1
| API Platform |	API Platform Web | 1.13.3-rc.2 | 1.14.13-rc.1
| API Platform |	API Manager Web	 | N/A	  | 1.2.7-rc.1
| API Platform |	Contract Caching Service |	1.0.5-rc.1 |	1.0.9-rc.1
| API Platform |	API Proxy Builder Service |	N/A |	1.0.4-rc.1
| API Platform |	Raml Parser Service |	1.0.11-rc.1 |	1.0.19-rc.1
| API Platform |	Proxies XAPI Service |	N/A |	1.0.0-rc.1
| API Designer |	VCS XAPI |	N/A |	3.2.0 / 3.3.0
| API Designer |	API Designer UI |	N/A |	2.2.7
| Design Center |	Mozart UI |	N/A |	1.4.0
| Design Center |	Mozart XAPI |	N/A |	v0.0.8
| Design Center	Mozart | Project Manager Service |	N/A |	v1.3.5
| Runtime Manager |	Cloudhub MCM |	v2.6.1-rc.1 |	2.8.0
| Runtime Manager |	Cloudhub UI |	v1.24.0-rc.3 / v1.24.0-rc.4 |	1.34.0
| Runtime Manager |	AMC UI Rest Facade |	v2.2.0-rc.1 |	v2.5.0
| Runtime Manager |	Hybrid Rest |	v2.6.4-rc.4 / v2.6.4 |	v2.13.1
| Runtime Manager |	Metadata Manager |	v1.3.1-hf.1 |	v1.6.0
| Runtime Manager |	Platform Alerts |	v1.2.1 |	v1.3.2
| Runtime Manager |	Mule Message Processor |	v1.1.0-rc.3 |	v1.1.1
| Runtime Manager |	Platform Messages |	v1.1.0 |	v1.2.0
| CS |	Authentication Server |	v0.27.3 |	v0.40.2
| CS |	Core Services UI |	v0.27.1 |	v0.40.0
| CS |	Anypoint signin |	v1.1.3 |	v1.8.0 / v1.8.1
| CS |	Landing Page UI |	v1.1.0-rc.5 |	v2.0.2-ms
| CS |	Navbar |	v0.7.0 |	v1.12.0
| CS |	Audit Log |	v1.5.0-rc.6 |	v1.7.1
| Exchange 1 |	Exchange 1 API |	v1.7.11-rc.1 |	1.7.11-rc.1
| Exchange 1 |	Exchange 1 UI |	1.7.2-rc.1 |	1.7.2-rc.1
| Exchange 2 |	API Metadata Service |	N/A |	0.7.x
| Exchange 2 |	Asset Manager Service |	N/A |	0.8.x
| Exchange 2 |	Asset Portal Service |	N/A |	0.6.x
| Exchange 2 |	Assets Reviews Service |	N/A |	0.6.x
| Exchange 2 |	Custom Assets Facade Service |	N/A |	0.8.x
| Exchange 2 |	Customization Service |	N/A |	0.5.x
| Exchange 2 |	Dependency Resolver Service |	N/A |	0.6.x
| Exchange 2 |	File Upload Service |	N/A |	0.5.x
| Exchange 2 |	Maven Facade Service |	N/A |	0.7.x
| Exchange 2 |	Rest Connect Service |	N/A |	0.4.x
| Exchange 2 |	Search Service |	N/A |	0.8.x
| Exchange 2 |	Tooling Service |	N/A |	0.3.x
| Exchange 2 |	Exchange UI |	N/A |	0.8.x
| Exchange 2 |	XAPI Service |	N/A |	0.8.x
| RAML Tooling |	API Notebook |	1.1.70 |	v1.1.70
| RAML Tooling |	Raml Mocking Service Site |	1.0.0 |	v1.2.352
| RAML Tooling |	Raml Mocking Service Proxy |	N/A |	v0.4.179
|===

See xref:1.6@upgrade.adoc[About Migrating Anypoint Platform Private Cloud Edition] for information on upgrading to version 1.6.1. See xref:1.7@upgrade.adoc[About Migrating Anypoint Platform Private Cloud Edition] for information on upgrading to version 1.7.1.

[WARNING]
During the migration process, there will be some downtime as each node is updated.

== Application Upgrades

The procedures in this topic describe how to migrate Anypoint Platform and the Anypoint Private Cloud edition infrastructure. You must also upgrade your applications to work with the new version of Anypoint Platform. Contact your customer success representative for more information.

== Prerequisites

Before migrating, ensure that you have performed and met the following prerequisites:

* Perform a backup of your system as described in xref:backup-and-disaster-recovery.adoc[About Backup and Recovery]. If you are upgrading from an older version that requires multiple intermediate upgrades you must backup each intermediate version before proceding to the next.

* Anypoint Private Cloud, version 2.0 requires that you have an NFS server installed and configured. Ensure that this is installed before beginning the upgrade. See xref:prereq-hardware.adoc[Private Cloud Edition Hardware Requirements]

* Ensure that your environment meets all of the system and network requirements described in xref:prereq-workflow.adoc[Workflow: Install and Verify Prerequisites for Physical Servers].

* Ensure that the necessary kernel modules are enabled as described in xref:prereq-software.adoc#kernel-modules[Software Requirements for Anypoint Private Cloud]. 

* Enable TCP ports `53`, `3011`, `3012` intra-node to allow communication with the database cluster.

* Ensure you have permission to run the `sudo` command on the node where you launch the migration tool.

* Ensure the `kubectl` command is available in the node where you are performing the migration. To verify that `kubectl` is installed, run the following:
+
----
$ sudo gravity enter
$ kubectl
----

== Procedure

. Obtain a link to the installer from your customer success representative.

. Use `ssh` to login to the master node of your cluster.
+
In a 3-node environment, all nodes are master nodes. To find the master nodes in a 6-node environment, run the following command:
+
----
kubectl get node --show-labels | grep gravitational.io/k8s-role=master
----
+
By performing these procedures from the master node, the upgrade scripts are able to update the entire platform.

. Uncompress the application archive.
+
----
tar -xvf anypoint-2.0.0-installer.tar.gz
----

. Navigate to the `anypoint-2.0.0` directory, then run the upload script.
+
----
cd anypoint-2.0.0
sudo ./upgrade
----
+
This command updates the platform to the current version and restarts each pod in the cluster.
+
----
$ sudo ./upgrade
----
+
This command produces output similar to the following:
+
----
-> initializing upload
-> uploading update package
importing anypoint:2.0.0
Thu Aug 23 09:36:30 UTC	Synchronizing application with Docker registry x.x.x.xxx:5000
Thu Aug 23 09:44:27 UTC	Synchronizing application with Docker registry x.x.x.xxx:5000
Thu Aug 23 09:51:29 UTC	Synchronizing application with Docker registry x.x.x.xxx:5000
Thu Aug 23 09:58:23 UTC	Application has been uploaded
updating anypoint from 1.7.1 to 2.0.0-xxxxxxxxxxxx
update operation (d077277f-3c69-4336-82bf-bd8b428ae202) has been started
the cluster is updating in background
----
+
Depending on your network configuration, this command may take a while to complete. Wait until the command finishes before proceeding to the next step.

. Verify that the migration was successful by performing one of the following:
+
* Run the following command from the node where you performed the upgrade:
+
----
$ sudo gravity enter
$ kubectl get pods
----
+
* Login to the Ops Center at the following URL:
+
----
https://{platform-host}:9500
----
+
[WARNING]
Before accessing Anypoint Platform, ensure that you configure your NSF server s described in the following step. Failure to configure NFS before accessing the platform may result in data loss.

. Configure Anypoint Private Cloud to use your NFS server.
+
After upgrading Anypoing Private Cloud, you configure it to use the required NFS server.
+
.. From Anypoint Platform, select *Access Management*.
.. Click *NFS Settings*.
.. Enter the domain name of your NFS server.
.. Enter the path to your NFS server.
.. Click *Save*.
.. Click *Test NFS Server* to test that your NFS server is configured correctly.
