= Upgrade Anypoint Platform Private Cloud
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Before You Begin
Because Anypoint Platform Private Cloud Edition (Anypoint Platform PCE) upgrades require a working installation, all environment prerequisites should already be met. As long as you (or your infrastructure team) successfully performed all prerequisite tasks listed in xref:prereq-hardware.adoc[Hardware Prerequisites], xref:prereq-software.adoc[Software Prerequisites], and xref:prereq-network.adoc[Network Prerequisites] prior to the installation of Anypoint Platform PCE, your environment can be upgraded successfully.

[NOTE]
If you are upgrading from Anypoint Platform PCE1.7.x to 2.0.x, an NFS server is required. Refer to xref:verify-nfs.adoc[NFS Server Prerequisites].

Refer to the xref:release-notes::pce/anypoint-private-cloud-2.0.3-release-notes#upgrade-paths[Upgrade Paths) section in the Anypoint Platform PCE release notes for additional information about upgrading Anypoint Platform PCE to the most recent version.

See xref:1.6@upgrade.adoc[About Migrating Anypoint Platform Private Cloud] for information on upgrading to version 1.6.1. See xref:1.7@upgrade.adoc[About Migrating Anypoint Platform Private Cloud] for information on upgrading to version 1.7.1.

Contact MuleSoft professional services prior to upgrading for assistance.

== Procedure

The following steps describe how to upgrade Anypoint Platform PCE and the Anypoint Platform PCE infrastructure. 

[NOTE]
====
* During an upgrade, all Anypoint Platform PCE components are updated.
* The upgrade process causes downtime for each node as it is updated.
====

. Perform a backup of your system as described in xref:backup-and-disaster-recovery.adoc[Configure Backup and Restore]. If you are upgrading from an older version that requires multiple intermediate upgrades, you must backup each intermediate version before proceeding to the next.

. Obtain a link to the installer from your customer success representative.

. Use `ssh` to log in to the master node of your cluster.
+
In a 3-node environment, all nodes are master nodes. To find the master nodes in a 6-node environment, run the following command:
+
----
kubectl get node --show-labels | grep gravitational.io/k8s-role=master
----
+
By performing these procedures from the master node, the upgrade scripts are able to update the entire platform.

. Uncompress the application archive:
+
----
tar -xvf anypoint-2.0.0-installer.tar.gz
----

. Navigate to the `anypoint-2.0.0` directory and run the upload script:
+
----
cd anypoint-2.0.0
sudo ./upgrade
----
+
The `sudo ./upgrade` command updates the platform to the current version and restarts each pod in the cluster. Depending on your network configuration, this command may take a while to complete, and produces output similar to the following example:
+
----
-> initializing upload
-> uploading update package
importing anypoint:2.0.0
Thu Aug 23 09:36:30 UTC	Synchronizing application with Docker registry x.x.x.xxx:5000
Thu Aug 23 09:44:27 UTC	Synchronizing application with Docker registry x.x.x.xxx:5000
Thu Aug 23 09:51:29 UTC	Synchronizing application with Docker registry x.x.x.xxx:5000
Thu Aug 23 09:58:23 UTC	Application has been uploaded
updating anypoint from 1.7.1 to 2.0.0-xxxxxxxxxxxx
update operation (d077277f-3c69-4336-82bf-bd8b428ae202) has been started
the cluster is updating in background
----

. When the upgrade finishes, verify that the migration was successful by performing one of the following options:
+
* Run the following command from the node where you performed the upgrade:
+
----
$ sudo gravity enter
$ kubectl get pods
----

. Log in to the Ops Center at the following URL:
+
----
https://{platform-host}:9500
----
+
[WARNING]
If you are upgrading from Anypoint Platform PCE 1.7.x to 2.0.x, ensure that you configure your NSF servers described in the following step before accessing Anypoint Platform PCE. In this case, failure to configure NFS before accessing the platform can result in data loss.

. When upgrading from from Anypoint Platform PCE 1.7.x to 2.0.x, configure the required NFS server.
+
.. From Anypoint Platform, select *Access Management*.
.. Select *NFS Settings*.
.. Enter the domain name of your NFS server.
.. Enter the path to your NFS server.
.. Select *Save*.
.. Select *Test NFS Server* to test that your NFS server is configured correctly.

. Unless you are updating Anypoint Platform PCE from 2.0.x to 2.1.x, configure the following items:

** xref:access-management-dns.adoc[Configure DNS on Anypoint Private Cloud]
** xref:access-management-SMTP.adoc[Configure SMTP in Anypoint Private Cloud]
** xref:access-management-disclaimer.adoc[Configure a Disclaimer for Anypoint Private Cloud]
** xref:verify-nfs.adoc[NFS Server Prerequisites]

== See Also

* xref:config-workflow.adoc[Post-installation Tasks]
