= Upgrade Anypoint Platform Private Cloud
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This topic provides information about upgrading Anypoint Platform Private Cloud Edition to the most recent version with the following migration paths:

[%header%autowidth.spread]
|===
| Base Version | Intermediate Versions | Target Version | Comments
| 1.7.x | N/A | 2.0 | Direct upgrade is supported
| 1.6.x | 1.7.1 | 2.0 | Must upgrade to version 1.7.1
| 1.5.x | 1.6.1, 1.7.1 | 2.0 | Must upgrade to 1.6.1, then 1.7.1 before upgrading to 2.0.
|===

See xref:1.6@upgrade.adoc[About Migrating Anypoint Platform Private Cloud Edition] for information on upgrading to version 1.6.1. See xref:1.7@upgrade.adoc[About Migrating Anypoint Platform Private Cloud Edition] for information on upgrading to version 1.7.1.

[WARNING]
====
Before upgrading:

* Ensure your environment meets all requirements listed in the xref:install-checklist[Installation and Upgrade Checklist].
* Perform a backup of your system as described in xref:backup-and-disaster-recovery.adoc[About Backup and Recovery]. If you are upgrading from an older version that requires multiple intermediate upgrades you must backup each intermediate version before proceeding to the next.

During the upgrade process, there will be some downtime as each node is updated. 
====

== Application Upgrades

The procedures in this topic describe how to migrate Anypoint Platform and the Anypoint Private Cloud edition infrastructure. You must also upgrade your applications to work with the new version of Anypoint Platform. Contact your customer success representative for more information.

== Procedure

. Obtain a link to the installer from your customer success representative.

. Use `ssh` to login to the master node of your cluster.
+
In a 3-node environment, all nodes are master nodes. To find the master nodes in a 6-node environment, run the following command:
+
----
kubectl get node --show-labels | grep gravitational.io/k8s-role=master
----
+
By performing these procedures from the master node, the upgrade scripts are able to update the entire platform.

. Uncompress the application archive.
+
----
tar -xvf anypoint-2.0.0-installer.tar.gz
----

. Navigate to the `anypoint-2.0.0` directory, then run the upload script.
+
----
cd anypoint-2.0.0
sudo ./upgrade
----
+
This command updates the platform to the current version and restarts each pod in the cluster.
+
----
$ sudo ./upgrade
----
+
This command produces output similar to the following:
+
----
-> initializing upload
-> uploading update package
importing anypoint:2.0.0
Thu Aug 23 09:36:30 UTC	Synchronizing application with Docker registry x.x.x.xxx:5000
Thu Aug 23 09:44:27 UTC	Synchronizing application with Docker registry x.x.x.xxx:5000
Thu Aug 23 09:51:29 UTC	Synchronizing application with Docker registry x.x.x.xxx:5000
Thu Aug 23 09:58:23 UTC	Application has been uploaded
updating anypoint from 1.7.1 to 2.0.0-xxxxxxxxxxxx
update operation (d077277f-3c69-4336-82bf-bd8b428ae202) has been started
the cluster is updating in background
----
+
Depending on your network configuration, this command may take a while to complete. Wait until the command finishes before proceeding to the next step.

. Verify that the migration was successful by performing one of the following:
+
* Run the following command from the node where you performed the upgrade:
+
----
$ sudo gravity enter
$ kubectl get pods
----
+
* Login to the Ops Center at the following URL:
+
----
https://{platform-host}:9500
----
+
[WARNING]
Before accessing Anypoint Platform, ensure that you configure your NSF server s described in the following step. Failure to configure NFS before accessing the platform may result in data loss.

. Configure Anypoint Private Cloud to use your NFS server.
+
After upgrading Anypoing Private Cloud, configure it to use the required NFS server.
+
.. From Anypoint Platform, select *Access Management*.
.. Click *NFS Settings*.
.. Enter the domain name of your NFS server.
.. Enter the path to your NFS server.
.. Click *Save*.
.. Click *Test NFS Server* to test that your NFS server is configured correctly.

== See Also

* xref:prereq-gravity-check.adoc[Verify Environment After Installation or Upgrade]
