= Configuring and Testing the NFS Protocol
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Private Cloud Edition supports the Network File System (NFSv4) protocol.
//I'm assuming this whole thing is in reference to an existing NFS. It seems like this info is more around testing/performance/validating/troubleshooting. Probably need a different title. 

== Verify the Required Ports are Open

The NFS server requires ports 2049 and 111 to be open.
You can use the netcat tool to verify the required ports are open. The netcat tool is a computer networking utility used to read and write to network connections using TCP or UDP. 

To verify the required ports are open, execute the following commands:

- `nc -zvu <host_name> 111`
- `nc -zv <host_name> 2049`

When the responses are successful you receive a response like the following:

----
[ec2-user@ip-10-1-1-97 ~]$ nc -zv <nfs_host_name> 2049
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to 10.1.0.155:2049.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
----

== Mount the NFS Server

Mount the NFS server in a temporary directory on the host. Use the set of commands in this section to check that your NFS server has the correct permissions and policies to be used. 

//I don't get how this is checking that the NFS server has the correct permissions and policies. Or does this mean, you should just verify that you have the proper permissions to mount nfs?

. Switch to root by typing: +
`sudo su`
. To mount the NFS in a temporary directory, run the following commands and replace both the `<nfs-server>` and the `<nfs-path>` with your own values. +
Run: +
`mkdir -p /mnt/home` +
and then: +
`mount -t nfs4 -o proto=tcp,port=2049 <nfs-server>:<path> /mnt/home/`
. If the mount fails, it is possible you are missing some NFS-required libraries. If this happens, install them: +
`yum install nfs-utils nfs-utils-lib`

== Validate NFS Performance

Perform careful analysis of your environment, both from the client and from the server point of view for optimal NFS performance. 

The high level steps for validating NFS performance include the following:

. Perform some basic operations to test the performance and latency of your NFS server. Specifically, these operations will: +
* Transfer data from the client (Anypoint Platform environment) to the NFS server 
* Measure how long each transfer takes 
2. Then, to perform the inverse, to see how the Anypoint Platform handles NFS files transfers, `read` and `write` operations will be tested, with both large (128MB) and small (80KB) files.
3. The command `time dd if=/dev/zero of=/mnt/home/<nameOfFile> bs=<blockSize> count=<amountOfBlocks>` will be used for the performance testing of the NFS server to transfer files with: +
* Names `<nameOfFile>` 
* The block size and the amount of blocks of the transfer are `<blockSize>` and `<amountOfBlocks>`, respectively.

=== Writing and Reading Large files on the NFS server

These tests will be run using large files (128 MB each), a block size of 4 KB, and an amount of blocks of 32768. These tests are run by generating different files during the tests (one file per test).

. To start with the testing, create a directory where the NFS server will be mounted: +

----
sudo su
mkdir -p /mnt/home
----

. Mount the NFS server:
   
----
mount -t nfs4 -o proto=tcp,port=2049 <nfs-server>:<path> /mnt/home/
----

. Run the following command to perform writes (five files of 128MB each) on the NFS server:

----
time for i in {1..5}; do dd if=/dev/zero of=/mnt/home/greatfile$i.test bs=4k count=32768; done
----

The command outputs something like:

----
[root@ip-10-1-1-97 ec2-user]# time for i in {1..5}; do dd if=/dev/zero of=/mnt/home/greatfile$i.test bs=4k count=32768; done
32768+0 records in
32768+0 records out
134217728 bytes (134 MB) copied, 2.12805 s, 63.1 MB/s
.
.
.
real 0m8.378s
user 0m0.034s
sys 0m0.792s
----

==== Validation

The important parameter is the `real` one. It should be around 10 seconds.

. Umount the NFS server:

----
umount /mnt/home
----

. Mount the NFS server again with:

----
mount -t nfs4 -o proto=tcp,port=2049 <nfs-server>:<path> /mnt/home/
----

. Run the following command to perform reads from the NFS server:

----
time for i in {1..5}; do dd if=/mnt/home/greatfile$i.test of=/dev/null bs=4k; done
----

==== Validation 

The important parameter is the `real` one. It should be around 10 seconds.

Umount the NFS server to clear out any caches.

----
umount /mnt/home
----

=== Writing and Reading Small files on the NFS server

Perform the same type of testing you ran on large files with smaller files.  In this case, the tests are performed with file sizes of 80 KB, block size of 4 KB, and amount of blocks 20.

To start with the testing make sure you have the `/mnt/home` directory created in the previous test, and follow the steps below:

1. Mount the NFS server:
   
----
mount -t nfs4 -o proto=tcp,port=2049 <nfs-server>:<path> /mnt/home/
----

2. Run the following command to perform writes (five files of 80 KB each) on the NFS server:

----
time for i in {1..30}; do dd if=/dev/zero of=/mnt/home/smallfile$i.test bs=4k count=20; done
----

==== Validation

The important parameter is the `real` one. It should be around 2 seconds.

3. Umount the NFS server:

----
umount <nfs-server>
----

4. Mount the NFS server again with:

----
mount -t nfs4 -o proto=tcp,port=2049 <nfs-server>:<path> /mnt/home/
----

5. Run the following command to perform reads from the NFS server:

----
time for i in {1..30}; do dd if=/mnt/home/smallfile$i.test of=/dev/null bs=4k; done
----

==== Validation
//I don't get why this is repeated

The important parameter is the `real` one. It should be around 2 seconds.

When you finish the performance testing, delete the test files. Remove all generated files by running:

----
rm -f /mnt/home/*.test
----

Finally, umount the NFS server:

----
umount /mnt/home
----

